INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (irosati,Rosati Isabel);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (marianom,marianom,Menendez Mariano);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (gabriela,gabriela,Romero Gabriela);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (hcarball,hcarball,Carballo Hernán J.);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (eitu,Iturralde Ester);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (jdiaz,Diaz Javier);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (rwilliam,rwilliam,Williams Ricardo);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (lorenzo,Lorenzo Carlos);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (alejandr,alejandr,Delú Alejandro);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (noraer,Corsaro Nora);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (jsueyro,Sueyro Javier);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (jbellia,Bellia Javier);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (luiseli,Elissondo Luis);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (etej,Tejerina Edith);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (azoia,Zoia Oscar Ariel);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (hcferrei,hcferrei,Ferreyra Haydée);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (mcasa,Casamayor Luis);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (mmartin,Martin Marcela);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (dspagnuo,dspagnuo,Spagnuolo José Dario);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (marianom,marianom,Menendez Mariano);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (cesar,D´Onofrio Cesar);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (amcp,Canedo Peró Ana Maria);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (lgreco,Greco Lucrecia);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (gropolo,Ropolo Gabriel);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (lramirez,lramirez,Ramirez Leonardo);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (lujan,Gurmendi María de Luján);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (emarmont,emarmont,Marmonti Emiliano);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (ipineiro,ipineiro,Piñeiro Isabel);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (jbordon,Bordón Juan);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (rab,Biagiola Rodolfo);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (eugenio,Bellia Eugenio);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (omadsen,Madsen Osmar);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (hcobo,Cobo Hernán);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (mrossi,Rossi Marcela);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (jcortes,Cortés Jorgelina);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (otesta,Testa Oscar);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (Cdomina,Dómina Cecilia);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (arielj,Jerez Ariel);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (psenor,Paula Senor);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (etej,Tejerina Edith);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (jschmidt,jschmidt,Schmidt Juan Manuel);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (gdiloret,gdiloret,Di Loreto Guillermo);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (vmajorel,vmajorel,Majorel Virginia);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (gdiorio,Diorio Guillermo);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (marianao,marianao,Menendez Mariano);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (sjunca,Junca Sandra);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (gtrutner,gtrutner,Trutner Guillermo);
INSERT INTO apex_usuario (usuario, clave, nombre) VALUES (ccarolin,ccarolin,Carolina Creichmon);
