<?

class php_625
{
	static function get_metadatos()
	{
		return array (
  'info' => 
  array (
    'proyecto' => 'toba',
    'objeto' => '625',
    'anterior' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'objeto_cuadro',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'OBJETO - Prototipacion METODOS',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2004-09-11 06:25:42',
    'clase_editor_proyecto' => 'toba',
    'clase_editor_item' => '/admin/objetos/editores/cuadro',
    'clase_archivo' => 'nucleo/browser/clases/objeto_cuadro.php',
    'clase_vinculos' => '1',
    'clase_editor' => '/admin/objetos/editores/cuadro',
    'clase_icono' => 'objetos/cuadro.gif',
    'clase_descripcion_corta' => 'CUADRO',
    'clase_instanciador_proyecto' => 'toba',
    'clase_instanciador_item' => '/admin/objetos/instanciadores/cuadro',
    'objeto_existe_ayuda' => NULL,
  ),
  'info_cuadro' => 
  array (
    'titulo' => NULL,
    'subtitulo' => NULL,
    'sql' => 'SELECT objeto_proyecto,
objeto,
metodo,
descripcion,
orden
FROM apex_objeto_proto_metodo
%w%
ORDER BY orden;',
    'columnas_clave' => 'objeto_proyecto, objeto,metodo',
    'archivos_callbacks' => NULL,
    'ancho' => '600',
    'ordenar' => '1',
    'exportar_xls' => '1',
    'exportar_pdf' => NULL,
    'paginar' => NULL,
    'tamano_pagina' => NULL,
    'eof_invisible' => NULL,
    'eof_customizado' => 'No hay metodos definidos',
    'pdf_respetar_paginacion' => NULL,
    'pdf_propiedades' => '',
    'asociacion_columnas' => NULL,
  ),
  'info_cuadro_columna' => 
  array (
    0 => 
    array (
      'orden' => '1',
      'titulo' => 'Orden',
      'estilo' => 'col-tex-p1',
      'ancho' => '1',
      'valor_sql' => 'orden',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    1 => 
    array (
      'orden' => '2',
      'titulo' => 'Metodo',
      'estilo' => 'col-tex-p1',
      'ancho' => '150',
      'valor_sql' => 'metodo',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    2 => 
    array (
      'orden' => '2.5',
      'titulo' => 'Descripcion',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'descripcion',
      'valor_sql_formato' => 'html_br',
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    3 => 
    array (
      'orden' => '3',
      'titulo' => 'Editar',
      'estilo' => 'col-tex-p1',
      'ancho' => '1',
      'valor_sql' => NULL,
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => 'abm',
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => '1',
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
  ),
);
	}

}
?>