<?

class php_470
{
	static function get_metadatos()
	{
		return array (
  'info' => 
  array (
    'proyecto' => 'toba',
    'objeto' => '470',
    'anterior' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'objeto_cuadro',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'PROYECTO - Tarea',
    'titulo' => 'Tareas existentes',
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2004-07-22 00:44:12',
    'clase_editor_proyecto' => 'toba',
    'clase_editor_item' => '/admin/objetos/editores/cuadro',
    'clase_archivo' => 'nucleo/browser/clases/objeto_cuadro.php',
    'clase_vinculos' => '1',
    'clase_editor' => '/admin/objetos/editores/cuadro',
    'clase_icono' => 'objetos/cuadro.gif',
    'clase_descripcion_corta' => 'CUADRO',
    'clase_instanciador_proyecto' => 'toba',
    'clase_instanciador_item' => '/admin/objetos/instanciadores/cuadro',
    'objeto_existe_ayuda' => NULL,
  ),
  'info_cuadro' => 
  array (
    'titulo' => 'Tareas existentes',
    'subtitulo' => NULL,
    'sql' => 'SELECT t.proyecto as tarea_proyecto,
t.tarea as tarea,
tt.descripcion as tipo,
te.descripcion as estado,
tp.descripcion as prioridad,
t.version as version,
tm.descripcion as tema,
t.descripcion as descripcion
FROM apex_ap_tarea t,
apex_ap_tarea_tipo tt,
apex_ap_tarea_estado te,
apex_ap_tarea_prioridad tp,
apex_ap_tarea_tema tm
WHERE t.tarea_estado = te.tarea_estado
AND t.tarea_prioridad = tp.tarea_prioridad
AND t.tarea_tipo = tt.tarea_tipo
AND t.tarea_tema = tm.tarea_tema
%w% ;',
    'columnas_clave' => 'tarea_proyecto, tarea',
    'archivos_callbacks' => NULL,
    'ancho' => NULL,
    'ordenar' => '1',
    'exportar_xls' => '1',
    'exportar_pdf' => '1',
    'paginar' => '1',
    'tamano_pagina' => '30',
    'eof_invisible' => NULL,
    'eof_customizado' => 'No hay tareas ingresadas',
    'pdf_respetar_paginacion' => NULL,
    'pdf_propiedades' => NULL,
    'asociacion_columnas' => NULL,
  ),
  'info_cuadro_columna' => 
  array (
    0 => 
    array (
      'orden' => '0',
      'titulo' => 'Tipo',
      'estilo' => 'col-tex-p1',
      'ancho' => '1%',
      'valor_sql' => 'tipo',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    1 => 
    array (
      'orden' => '1',
      'titulo' => 'Estado',
      'estilo' => 'col-tex-p1',
      'ancho' => '1%',
      'valor_sql' => 'estado',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    2 => 
    array (
      'orden' => '2',
      'titulo' => 'Prioridad',
      'estilo' => 'col-tex-p1',
      'ancho' => '1%',
      'valor_sql' => 'prioridad',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    3 => 
    array (
      'orden' => '3',
      'titulo' => 'Version',
      'estilo' => 'col-tex-p1',
      'ancho' => '1%',
      'valor_sql' => 'version',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    4 => 
    array (
      'orden' => '3.5',
      'titulo' => 'Tema',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'tema',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    5 => 
    array (
      'orden' => '4',
      'titulo' => 'Descripcion',
      'estilo' => 'col-tex-p1',
      'ancho' => '99%',
      'valor_sql' => 'descripcion',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => '1',
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    6 => 
    array (
      'orden' => '5',
      'titulo' => 'd',
      'estilo' => 'col-tex-p1',
      'ancho' => '1%',
      'valor_sql' => NULL,
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => 'abm',
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => '1',
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
  ),
);
	}

}
?>