------------------------------------------------------------
--[1507]--  OBJETO - EI ci 
------------------------------------------------------------
INSERT INTO apex_objeto (proyecto, objeto, anterior, reflexivo, clase_proyecto, clase, subclase, subclase_archivo, objeto_categoria_proyecto, objeto_categoria, nombre, titulo, colapsable, descripcion, fuente_datos_proyecto, fuente_datos, solicitud_registrar, solicitud_obj_obs_tipo, solicitud_obj_observacion, parametro_a, parametro_b, parametro_c, parametro_d, parametro_e, parametro_f, usuario, creacion) VALUES ('toba', '1507', NULL, NULL, 'toba', 'objeto_datos_relacion', NULL, NULL, NULL, NULL, 'OBJETO - EI ci', NULL, NULL, NULL, 'toba', 'instancia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-08-19 17:28:22');
INSERT INTO apex_objeto_datos_rel (proyecto, objeto, clave, ap, ap_clase, ap_archivo) VALUES ('toba', '1507', 'objeto, proyecto', '2', NULL, NULL);
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba', '1507', '1', 'base -> dependencias', 'toba', '1501', 'base', 'proyecto,objeto', 'toba', '1502', 'dependencias', 'proyecto,objeto_consumidor', '0', '1');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba', '1507', '2', 'base -> eventos', 'toba', '1501', 'base', 'proyecto,objeto', 'toba', '1505', 'eventos', 'proyecto,objeto', '0', '2');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba', '1507', '3', 'base -> prop_basicas', 'toba', '1501', 'base', 'proyecto,objeto', 'toba', '1503', 'prop_basicas', 'objeto_mt_me_proyecto,objeto_mt_me', '0', '3');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba', '1507', '4', 'base -> pantalla', 'toba', '1503', 'prop_basicas', 'objeto_mt_me_proyecto,objeto_mt_me', 'toba', '1504', 'pantallas', 'objeto_ci_proyecto,objeto_ci', '0', '4');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba', '82', '1507', '1501', 'base', '1', '1', NULL, NULL, NULL);
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba', '83', '1507', '1502', 'dependencias', '0', '0', NULL, NULL, NULL);
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba', '84', '1507', '1505', 'eventos', '0', '0', NULL, NULL, NULL);
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba', '85', '1507', '1504', 'pantallas', '1', '0', NULL, NULL, NULL);
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba', '86', '1507', '1503', 'prop_basicas', '1', '1', NULL, NULL, NULL);
