<?php

class catalogo_general
{
	static function get_tablas()
	{
		return array (
  0 => 'apex_revision',
  1 => 'apex_instancia',
  2 => 'apex_estilo',
  3 => 'apex_menu',
  4 => 'apex_proyecto',
  5 => 'apex_log_sistema_tipo',
  6 => 'apex_fuente_datos_motor',
  7 => 'apex_fuente_datos',
  8 => 'apex_grafico',
  9 => 'apex_recurso_origen',
  10 => 'apex_nivel_acceso',
  11 => 'apex_solicitud_tipo',
  12 => 'apex_elemento_formulario',
  13 => 'apex_solicitud_obs_tipo',
  14 => 'apex_pagina_tipo',
  15 => 'apex_columna_estilo',
  16 => 'apex_columna_formato',
  17 => 'apex_usuario_tipodoc',
  18 => 'apex_usuario',
  19 => 'apex_usuario_perfil_datos',
  20 => 'apex_usuario_grupo_acc',
  21 => 'apex_usuario_proyecto',
  22 => 'apex_item_zona',
  23 => 'apex_item',
  24 => 'apex_item_info',
  25 => 'apex_clase_tipo',
  26 => 'apex_clase',
  27 => 'apex_objeto',
  28 => 'apex_objeto_info',
  29 => 'apex_objeto_dependencias',
  30 => 'apex_objeto_eventos',
  31 => 'apex_item_objeto',
  32 => 'apex_usuario_grupo_acc_item',
  33 => 'apex_arbol_items_fotos',
  34 => 'apex_admin_album_fotos',
  35 => 'apex_admin_param_previsualizazion',
  36 => 'apex_conversion',
  37 => 'apex_solicitud',
  38 => 'apex_sesion_browser',
  39 => 'apex_solicitud_browser',
  40 => 'apex_solicitud_consola',
  41 => 'apex_solicitud_cronometro',
  42 => 'apex_solicitud_observacion',
  43 => 'apex_log_objeto',
  44 => 'apex_log_sistema',
  45 => 'apex_log_error_login',
  46 => 'apex_log_ip_rechazada',
  47 => 'apex_nota_tipo',
  48 => 'apex_nota',
  49 => 'apex_item_nota',
  50 => 'apex_objeto_nota',
  51 => 'apex_msg_tipo',
  52 => 'apex_msg',
  53 => 'apex_item_msg',
  54 => 'apex_objeto_msg',
  55 => 'apex_permiso',
  56 => 'apex_permiso_grupo_acc',
  57 => 'apex_objeto_mt_me_tipo_nav',
  58 => 'apex_objeto_mt_me',
  59 => 'apex_objeto_ci_pantalla',
  60 => 'apex_objeto_cuadro',
  61 => 'apex_objeto_cuadro_cc',
  62 => 'apex_objeto_ei_cuadro_columna',
  63 => 'apex_objeto_ut_formulario',
  64 => 'apex_objeto_ei_formulario_ef',
  65 => 'apex_objeto_esquema',
  66 => 'apex_admin_persistencia',
  67 => 'apex_tipo_datos',
  68 => 'apex_objeto_db_registros',
  69 => 'apex_objeto_db_registros_col',
  70 => 'apex_objeto_db_registros_ext',
  71 => 'apex_objeto_db_registros_ext_col',
  72 => 'apex_objeto_datos_rel',
  73 => 'apex_objeto_datos_rel_asoc',
);
	}

}
?>