<?php

class toba_db_catalogo_general
{
	static function get_tablas()
	{
		return array (
  0 => 'apex_revision',
  1 => 'apex_instancia',
  2 => 'apex_proyecto',
  3 => 'apex_menu',
  4 => 'apex_estilo',
  5 => 'apex_log_sistema_tipo',
  6 => 'apex_fuente_datos_motor',
  7 => 'apex_fuente_datos',
  8 => 'apex_grafico',
  9 => 'apex_recurso_origen',
  10 => 'apex_nivel_acceso',
  11 => 'apex_solicitud_tipo',
  12 => 'apex_elemento_formulario',
  13 => 'apex_solicitud_obs_tipo',
  14 => 'apex_pagina_tipo',
  15 => 'apex_columna_estilo',
  16 => 'apex_columna_formato',
  17 => 'apex_ptos_control',
  18 => 'apex_ptos_control_param',
  19 => 'apex_ptos_control_ctrl',
  20 => 'apex_consulta_php',
  21 => 'apex_usuario_tipodoc',
  22 => 'apex_usuario',
  23 => 'apex_item_zona',
  24 => 'apex_item',
  25 => 'apex_item_info',
  26 => 'apex_clase_tipo',
  27 => 'apex_clase',
  28 => 'apex_clase_relacion',
  29 => 'apex_objeto',
  30 => 'apex_objeto_info',
  31 => 'apex_objeto_dependencias',
  32 => 'apex_objeto_eventos',
  33 => 'apex_ptos_control_x_evento',
  34 => 'apex_item_objeto',
  35 => 'apex_log_objeto',
  36 => 'apex_arbol_items_fotos',
  37 => 'apex_admin_album_fotos',
  38 => 'apex_admin_param_previsualizazion',
  39 => 'apex_conversion',
  40 => 'apex_solicitud',
  41 => 'apex_sesion_browser',
  42 => 'apex_solicitud_browser',
  43 => 'apex_solicitud_consola',
  44 => 'apex_solicitud_cronometro',
  45 => 'apex_solicitud_observacion',
  46 => 'apex_log_sistema',
  47 => 'apex_log_error_login',
  48 => 'apex_log_ip_rechazada',
  49 => 'apex_msg_tipo',
  50 => 'apex_msg',
  51 => 'apex_item_msg',
  52 => 'apex_objeto_msg',
  53 => 'apex_nota_tipo',
  54 => 'apex_nota',
  55 => 'apex_item_nota',
  56 => 'apex_objeto_nota',
  57 => 'apex_relacion_tablas',
  58 => 'apex_dimension',
  59 => 'apex_dimension_gatillo',
  60 => 'apex_objeto_mt_me_tipo_nav',
  61 => 'apex_objeto_mt_me',
  62 => 'apex_objeto_ci_pantalla',
  63 => 'apex_objeto_cuadro',
  64 => 'apex_objeto_cuadro_cc',
  65 => 'apex_objeto_ei_cuadro_columna',
  66 => 'apex_objeto_ut_formulario',
  67 => 'apex_objeto_ei_formulario_ef',
  68 => 'apex_objeto_esquema',
  69 => 'apex_admin_persistencia',
  70 => 'apex_tipo_datos',
  71 => 'apex_objeto_db_registros',
  72 => 'apex_objeto_db_registros_col',
  73 => 'apex_objeto_db_registros_ext',
  74 => 'apex_objeto_db_registros_ext_col',
  75 => 'apex_objeto_db_registros_uniq',
  76 => 'apex_objeto_datos_rel',
  77 => 'apex_objeto_datos_rel_asoc',
  78 => 'apex_molde_opciones_generacion',
  79 => 'apex_molde_operacion_tipo',
  80 => 'apex_molde_operacion_tipo_dato',
  81 => 'apex_molde_operacion',
  82 => 'apex_molde_operacion_log',
  83 => 'apex_molde_operacion_log_elementos',
  84 => 'apex_molde_operacion_abms',
  85 => 'apex_molde_operacion_abms_fila',
  86 => 'apex_permiso',
  87 => 'apex_usuario_perfil_datos',
  88 => 'apex_usuario_perfil_datos_dims',
  89 => 'apex_usuario_grupo_acc',
  90 => 'apex_usuario_grupo_acc_item',
  91 => 'apex_permiso_grupo_acc',
  92 => 'apex_restriccion_funcional',
  93 => 'apex_grupo_acc_restriccion_funcional',
  94 => 'apex_restriccion_funcional_ef',
  95 => 'apex_restriccion_funcional_pantalla',
  96 => 'apex_restriccion_funcional_evt',
  97 => 'apex_restriccion_funcional_ei',
  98 => 'apex_restriccion_funcional_cols',
  99 => 'apex_usuario_proyecto',
  100 => 'apex_usuario_proyecto_perfil_datos',
);
	}

}

?>