<?php

class toba_db_catalogo_general
{
	static function get_tablas()
	{
		return array (
  0 => 'apex_admin_persistencia',
  1 => 'apex_tipo_datos',
  2 => 'apex_objeto_db_registros',
  3 => 'apex_objeto_db_registros_col',
  4 => 'apex_objeto_db_registros_ext',
  5 => 'apex_objeto_db_registros_ext_col',
  6 => 'apex_objeto_db_registros_uniq',
  7 => 'apex_objeto_datos_rel',
  8 => 'apex_objeto_datos_rel_asoc',
  9 => 'apex_nota_tipo',
  10 => 'apex_nota',
  11 => 'apex_item_nota',
  12 => 'apex_objeto_nota',
  13 => 'apex_objeto_esquema',
  14 => 'apex_solicitud',
  15 => 'apex_sesion_browser',
  16 => 'apex_solicitud_browser',
  17 => 'apex_solicitud_consola',
  18 => 'apex_solicitud_cronometro',
  19 => 'apex_solicitud_observacion',
  20 => 'apex_log_sistema',
  21 => 'apex_log_error_login',
  22 => 'apex_log_ip_rechazada',
  23 => 'apex_item_zona',
  24 => 'apex_item',
  25 => 'apex_item_info',
  26 => 'apex_clase_tipo',
  27 => 'apex_clase',
  28 => 'apex_clase_relacion',
  29 => 'apex_objeto',
  30 => 'apex_objeto_info',
  31 => 'apex_objeto_dependencias',
  32 => 'apex_objeto_eventos',
  33 => 'apex_ptos_control_x_evento',
  34 => 'apex_item_objeto',
  35 => 'apex_log_objeto',
  36 => 'apex_arbol_items_fotos',
  37 => 'apex_admin_album_fotos',
  38 => 'apex_admin_param_previsualizazion',
  39 => 'apex_conversion',
  40 => 'apex_revision',
  41 => 'apex_instancia',
  42 => 'apex_proyecto',
  43 => 'apex_objeto_cuadro',
  44 => 'apex_objeto_cuadro_cc',
  45 => 'apex_objeto_ei_cuadro_columna',
  46 => 'apex_permiso',
  47 => 'apex_molde_opciones_generacion',
  48 => 'apex_molde_operacion_tipo',
  49 => 'apex_molde_operacion_tipo_dato',
  50 => 'apex_molde_operacion',
  51 => 'apex_molde_operacion_log',
  52 => 'apex_molde_operacion_log_elementos',
  53 => 'apex_molde_operacion_abms',
  54 => 'apex_molde_operacion_abms_fila',
  55 => 'apex_usuario_tipodoc',
  56 => 'apex_usuario',
  57 => 'apex_usuario_perfil_datos',
  58 => 'apex_usuario_grupo_acc',
  59 => 'apex_usuario_proyecto',
  60 => 'apex_usuario_grupo_acc_item',
  61 => 'apex_permiso_grupo_acc',
  62 => 'apex_menu',
  63 => 'apex_estilo',
  64 => 'apex_log_sistema_tipo',
  65 => 'apex_fuente_datos_motor',
  66 => 'apex_fuente_datos',
  67 => 'apex_grafico',
  68 => 'apex_recurso_origen',
  69 => 'apex_nivel_acceso',
  70 => 'apex_solicitud_tipo',
  71 => 'apex_elemento_formulario',
  72 => 'apex_solicitud_obs_tipo',
  73 => 'apex_pagina_tipo',
  74 => 'apex_columna_estilo',
  75 => 'apex_columna_formato',
  76 => 'apex_ptos_control',
  77 => 'apex_ptos_control_param',
  78 => 'apex_ptos_control_ctrl',
  79 => 'apex_consulta_php',
  80 => 'apex_msg_tipo',
  81 => 'apex_msg',
  82 => 'apex_item_msg',
  83 => 'apex_objeto_msg',
  84 => 'apex_objeto_ut_formulario',
  85 => 'apex_objeto_ei_formulario_ef',
  86 => 'apex_objeto_mt_me_tipo_nav',
  87 => 'apex_objeto_mt_me',
  88 => 'apex_objeto_ci_pantalla',
);
	}

}

?>