INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_buffer', 'Editor de buffer', NULL, 'nucleo/browser/zona/zona_buffer.php', 'APEX - Contexto BUFFER');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_carpeta', 'Editor de carpetas', NULL, 'nucleo/browser/zona/zona_carpeta.php', NULL);
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_clase', 'Editor de clase', NULL, 'nucleo/browser/zona/zona_clase.php', 'APEX - Contexto CLASE');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_dimension', 'Editor de dimension', NULL, 'nucleo/browser/zona/zona_dimension.php', 'APEX - Contexto DIMENSION');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_fuente', 'Editor de fuente', NULL, 'nucleo/browser/zona/zona_fuente.php', 'APEX - Contexto FUENTE');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_grupo_acceso', 'Editor de usuario_grupo', NULL, 'nucleo/browser/zona/zona_grupo_acceso.php', 'APEX - Contexto USUARIO-GRUPO');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_item', 'Edicion de ITEMs', NULL, 'nucleo/browser/zona/zona_item.php', 'Esta zona representa el entorno en el que se edita un item');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_nucleo', 'Editor de nucleo', NULL, 'nucleo/browser/zona/zona_nucleo.php', 'APEX - Contexto NUCLEO');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_objeto', 'Edicion de Objetos', 'proyecto, objeto', 'nucleo/browser/zona/zona_objeto.php', NULL);
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_patron', 'Editor de patron', NULL, 'nucleo/browser/zona/zona_patron.php', 'APEX - Contexto PATRON');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_proyecto', 'Editor de proyecto', NULL, 'nucleo/browser/zona/zona_proyecto.php', 'APEX - Contexto PROYECTO');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_trabajo', 'Lugar de TRABAJO', NULL, 'nucleo/browser/zona/zona_trabajo.php', 'APEX - Lugar de Trabajo');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_usuario', 'Editor de usuario', NULL, 'nucleo/browser/zona/zona_usuario.php', 'APEX - Contexto USUARIO');
INSERT INTO apex_item_zona (proyecto, zona, nombre, clave_editable, archivo, descripcion) VALUES ('toba', 'zona_usuario_perfil', 'Editor de usuario_perfil', NULL, 'nucleo/browser/zona/zona_perfil_datos.php', 'APEX - Contexto USUARIO-
PERFIL');
