<?

class php_1523
{
	static function get_metadatos()
	{
		return array (
  'info' => 
  array (
    'proyecto' => 'toba',
    'objeto' => '1523',
    'anterior' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'objeto_datos_tabla',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'OBJETO - EI cuadro',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2005-08-28 03:13:38',
    'clase_editor_proyecto' => 'toba',
    'clase_editor_item' => '/admin/objetos_toba/editores/db_registros',
    'clase_archivo' => 'nucleo/persistencia/objeto_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '/admin/objetos_toba/editores/db_registros',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'Objeto DATOS - TABLA',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
  ),
  'info_estructura' => 
  array (
    'tabla' => 'apex_objeto_cuadro',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => '1',
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => NULL,
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/persistencia/ap_tabla_db_s.php',
  ),
  'info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '104',
      'columna' => 'objeto_cuadro_proyecto',
      'tipo' => 'C',
      'pk' => '1',
      'secuencia' => NULL,
      'largo' => '15',
      'no_nulo' => NULL,
      'no_nulo_db' => '1',
      'externa' => NULL,
    ),
    1 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '105',
      'columna' => 'objeto_cuadro',
      'tipo' => 'E',
      'pk' => '1',
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => '1',
      'externa' => NULL,
    ),
    2 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '106',
      'columna' => 'titulo',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '80',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    3 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '107',
      'columna' => 'subtitulo',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '80',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    4 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '108',
      'columna' => 'sql',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '-1',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    5 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '109',
      'columna' => 'columnas_clave',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '255',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    6 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '110',
      'columna' => 'clave_dbr',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    7 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '111',
      'columna' => 'archivos_callbacks',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '100',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    8 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '112',
      'columna' => 'ancho',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '10',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    9 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '113',
      'columna' => 'ordenar',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    10 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '114',
      'columna' => 'paginar',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    11 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '115',
      'columna' => 'tamano_pagina',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    12 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '116',
      'columna' => 'eof_invisible',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    13 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '117',
      'columna' => 'eof_customizado',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '255',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    14 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '118',
      'columna' => 'exportar',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    15 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '119',
      'columna' => 'exportar_rtf',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    16 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '120',
      'columna' => 'pdf_propiedades',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '-1',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    17 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '121',
      'columna' => 'pdf_respetar_paginacion',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    18 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '122',
      'columna' => 'asociacion_columnas',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '100',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    19 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '123',
      'columna' => 'ev_seleccion',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    20 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '124',
      'columna' => 'ev_eliminar',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    21 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '125',
      'columna' => 'dao_nucleo_proyecto',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '15',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    22 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '126',
      'columna' => 'dao_nucleo',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '60',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    23 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '127',
      'columna' => 'dao_metodo',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '80',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    24 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '128',
      'columna' => 'dao_parametros',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '150',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    25 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '129',
      'columna' => 'desplegable',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    26 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '130',
      'columna' => 'desplegable_activo',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    27 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '131',
      'columna' => 'scroll',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    28 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '132',
      'columna' => 'scroll_alto',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '10',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    29 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '227',
      'columna' => 'tipo_paginado',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '1',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    30 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '296',
      'columna' => 'cc_modo',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '1',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    31 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '297',
      'columna' => 'cc_modo_anidado_colap',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '1',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    32 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '298',
      'columna' => 'cc_modo_anidado_totcol',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '1',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    33 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1523',
      'col_id' => '299',
      'columna' => 'cc_modo_anidado_totcua',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '1',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
  ),
);
	}

}
?>