<?php

class toba_mc_comp__1532
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'toba_editor',
    'objeto' => 1532,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_relacion',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'Comp. datos_relacion',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba_editor',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2005-08-28 03:39:13',
    'punto_montaje' => 12,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000251',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_relacion.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000251',
    'clase_icono' => 'objetos/datos_relacion.gif',
    'clase_descripcion_corta' => 'datos_relacion',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => 'ap_relacion_objeto',
    'ap_archivo' => 'db/ap_relacion_objeto.php',
    'ap_punto_montaje' => 12,
    'cant_dependencias' => 5,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'proyecto' => 'toba_editor',
    'objeto' => 1532,
    'debug' => 0,
    'ap' => 3,
    'punto_montaje' => 12,
    'ap_clase' => 'ap_relacion_objeto',
    'ap_archivo' => 'db/ap_relacion_objeto.php',
    'sinc_susp_constraints' => 0,
    'sinc_orden_automatico' => 1,
    'sinc_lock_optimista' => 1,
  ),
  '_info_relaciones' => 
  array (
    0 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'asoc_id' => 4,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1501,
      'padre_id' => 'base',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1525,
      'hijo_id' => 'prop_basicas',
      'cascada' => 0,
      'orden' => '1',
    ),
    1 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'asoc_id' => 5,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1525,
      'padre_id' => 'prop_basicas',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1526,
      'hijo_id' => 'relaciones',
      'cascada' => 0,
      'orden' => '3',
    ),
    2 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'asoc_id' => 6,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1501,
      'padre_id' => 'base',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1502,
      'hijo_id' => 'dependencias',
      'cascada' => 0,
      'orden' => '2',
    ),
    3 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'asoc_id' => 33000008,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1526,
      'padre_id' => 'relaciones',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 33000012,
      'hijo_id' => 'columnas_relacion',
      'cascada' => NULL,
      'orden' => '4',
    ),
  ),
  '_info_dependencias' => 
  array (
    0 => 
    array (
      'identificador' => 'base',
      'proyecto' => 'toba_editor',
      'objeto' => 1501,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '1',
      'parametros_b' => '1',
    ),
    1 => 
    array (
      'identificador' => 'relaciones',
      'proyecto' => 'toba_editor',
      'objeto' => 1526,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    2 => 
    array (
      'identificador' => 'prop_basicas',
      'proyecto' => 'toba_editor',
      'objeto' => 1525,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '1',
      'parametros_b' => '1',
    ),
    3 => 
    array (
      'identificador' => 'dependencias',
      'proyecto' => 'toba_editor',
      'objeto' => 1502,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    4 => 
    array (
      'identificador' => 'columnas_relacion',
      'proyecto' => 'toba_editor',
      'objeto' => 33000012,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '0',
      'parametros_b' => '0',
    ),
  ),
  '_info_columnas_asoc_rel' => 
  array (
    0 => 
    array (
      'asoc_id' => 4,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 149,
      'hijo_objeto' => 1525,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1501,
      'padre_clave' => 21,
      'col_padre' => 'proyecto',
    ),
    1 => 
    array (
      'asoc_id' => 4,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 150,
      'hijo_objeto' => 1525,
      'col_hija' => 'objeto',
      'padre_objeto' => 1501,
      'padre_clave' => 22,
      'col_padre' => 'objeto',
    ),
    2 => 
    array (
      'asoc_id' => 5,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 155,
      'hijo_objeto' => 1526,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1525,
      'padre_clave' => 149,
      'col_padre' => 'proyecto',
    ),
    3 => 
    array (
      'asoc_id' => 5,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 156,
      'hijo_objeto' => 1526,
      'col_hija' => 'objeto',
      'padre_objeto' => 1525,
      'padre_clave' => 150,
      'col_padre' => 'objeto',
    ),
    4 => 
    array (
      'asoc_id' => 6,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 48,
      'hijo_objeto' => 1502,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1501,
      'padre_clave' => 21,
      'col_padre' => 'proyecto',
    ),
    5 => 
    array (
      'asoc_id' => 6,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 49,
      'hijo_objeto' => 1502,
      'col_hija' => 'objeto_consumidor',
      'padre_objeto' => 1501,
      'padre_clave' => 22,
      'col_padre' => 'objeto',
    ),
    6 => 
    array (
      'asoc_id' => 33000008,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 33000023,
      'hijo_objeto' => 33000012,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1526,
      'padre_clave' => 155,
      'col_padre' => 'proyecto',
    ),
    7 => 
    array (
      'asoc_id' => 33000008,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 33000022,
      'hijo_objeto' => 33000012,
      'col_hija' => 'objeto',
      'padre_objeto' => 1526,
      'padre_clave' => 156,
      'col_padre' => 'objeto',
    ),
    8 => 
    array (
      'asoc_id' => 33000008,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 33000021,
      'hijo_objeto' => 33000012,
      'col_hija' => 'asoc_id',
      'padre_objeto' => 1526,
      'padre_clave' => 157,
      'col_padre' => 'asoc_id',
    ),
    9 => 
    array (
      'asoc_id' => 33000008,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 33000026,
      'hijo_objeto' => 33000012,
      'col_hija' => 'padre_objeto',
      'padre_objeto' => 1526,
      'padre_clave' => 160,
      'col_padre' => 'padre_objeto',
    ),
    10 => 
    array (
      'asoc_id' => 33000008,
      'proyecto' => 'toba_editor',
      'objeto' => 1532,
      'hijo_clave' => 33000025,
      'hijo_objeto' => 33000012,
      'col_hija' => 'hijo_objeto',
      'padre_objeto' => 1526,
      'padre_clave' => 164,
      'col_padre' => 'hijo_objeto',
    ),
  ),
);
	}

}

?>