<?php

class toba_mc_comp__1524
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'toba_editor',
    'objeto' => 1524,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_tabla',
    'subclase' => 'odt_cuadro_columnas',
    'subclase_archivo' => 'db/odt_cuadro_columnas.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'OBJETO - EI cuadro col.',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba_editor',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2005-08-28 03:15:18',
    'punto_montaje' => 12,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000250',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000250',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'datos_tabla',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => 'dt_ap_cuadro_columnas',
    'ap_archivo' => 'db/dt_ap_cuadro_columnas.php',
    'ap_punto_montaje' => 12,
    'cant_dependencias' => 0,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'tabla' => 'apex_objeto_ei_cuadro_columna',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => 0,
    'punto_montaje' => 12,
    'ap_sub_clase' => 'dt_ap_cuadro_columnas',
    'ap_sub_clase_archivo' => 'db/dt_ap_cuadro_columnas.php',
    'ap_modificar_claves' => 0,
    'ap_clase' => 'especifico',
    'ap_clase_archivo' => 'ad-hoc',
    'tabla_ext' => NULL,
    'esquema' => NULL,
    'esquema_ext' => NULL,
  ),
  '_info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 133,
      'columna' => 'objeto_cuadro_proyecto',
      'tipo' => 'C',
      'pk' => 1,
      'secuencia' => NULL,
      'largo' => 15,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    1 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 134,
      'columna' => 'objeto_cuadro',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    2 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 135,
      'columna' => 'objeto_cuadro_col',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => 'apex_obj_ei_cuadro_col_seq',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    3 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 136,
      'columna' => 'clave',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => 40,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    4 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 137,
      'columna' => 'orden',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    5 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 138,
      'columna' => 'titulo',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => 100,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    6 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 139,
      'columna' => 'estilo',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    7 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 140,
      'columna' => 'ancho',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => 10,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    8 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 141,
      'columna' => 'formateo',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    9 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 142,
      'columna' => 'vinculo_indice',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => 20,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    10 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 143,
      'columna' => 'no_ordenar',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    11 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 144,
      'columna' => 'mostrar_xls',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    12 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 145,
      'columna' => 'mostrar_pdf',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    13 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 146,
      'columna' => 'pdf_propiedades',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    14 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 147,
      'columna' => 'desabilitado',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    15 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 148,
      'columna' => 'total',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    16 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 226,
      'columna' => 'estilo_titulo',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    17 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 295,
      'columna' => 'total_cc',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => 100,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    18 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 601,
      'columna' => 'usar_vinculo',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    19 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 602,
      'columna' => 'vinculo_carpeta',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 60,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    20 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 603,
      'columna' => 'vinculo_item',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 60,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    21 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 604,
      'columna' => 'vinculo_popup',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    22 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 605,
      'columna' => 'vinculo_popup_param',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 100,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    23 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 606,
      'columna' => 'vinculo_target',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 40,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    24 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 607,
      'columna' => 'vinculo_celda',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 40,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    25 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 30000004,
      'columna' => 'permitir_html',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    26 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 30000005,
      'columna' => 'grupo',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => 255,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    27 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 33000002,
      'columna' => 'vinculo_servicio',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => 100,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    28 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1524,
      'col_id' => 33000041,
      'columna' => 'evento_asociado',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
  ),
  '_info_externas' => 
  array (
  ),
  '_info_externas_col' => 
  array (
  ),
  '_info_valores_unicos' => 
  array (
    0 => 
    array (
      'columnas' => 'clave',
    ),
  ),
  '_info_fks' => 
  array (
  ),
);
	}

}

?>