<?php

class toba_mc_comp__1507
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'toba_editor',
    'objeto' => 1507,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_relacion',
    'subclase' => 'odr_ci',
    'subclase_archivo' => 'db/odr_ci.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'Comp. ci',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba_editor',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2005-08-19 17:28:22',
    'punto_montaje' => 12,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000251',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_relacion.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000251',
    'clase_icono' => 'objetos/datos_relacion.gif',
    'clase_descripcion_corta' => 'datos_relacion',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => 'ap_relacion_objeto',
    'ap_archivo' => 'db/ap_relacion_objeto.php',
    'ap_punto_montaje' => 12,
    'cant_dependencias' => 8,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'proyecto' => 'toba_editor',
    'objeto' => 1507,
    'debug' => 0,
    'ap' => 3,
    'punto_montaje' => 12,
    'ap_clase' => 'ap_relacion_objeto',
    'ap_archivo' => 'db/ap_relacion_objeto.php',
    'sinc_susp_constraints' => 0,
    'sinc_orden_automatico' => 1,
    'sinc_lock_optimista' => 1,
  ),
  '_info_relaciones' => 
  array (
    0 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'asoc_id' => 1,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1501,
      'padre_id' => 'base',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1502,
      'hijo_id' => 'dependencias',
      'cascada' => 0,
      'orden' => '1',
    ),
    1 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'asoc_id' => 2,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1501,
      'padre_id' => 'base',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1505,
      'hijo_id' => 'eventos',
      'cascada' => 0,
      'orden' => '2',
    ),
    2 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'asoc_id' => 3,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1501,
      'padre_id' => 'base',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1503,
      'hijo_id' => 'prop_basicas',
      'cascada' => 0,
      'orden' => '3',
    ),
    3 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'asoc_id' => 4,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1503,
      'padre_id' => 'prop_basicas',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1504,
      'hijo_id' => 'pantallas',
      'cascada' => 0,
      'orden' => '4',
    ),
    4 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'asoc_id' => 10000009,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1505,
      'padre_id' => 'eventos',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 10000033,
      'hijo_id' => 'puntos_control',
      'cascada' => NULL,
      'orden' => '5',
    ),
    5 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'asoc_id' => 33000004,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1502,
      'padre_id' => 'dependencias',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 33000010,
      'hijo_id' => 'objetos_pantalla',
      'cascada' => NULL,
      'orden' => '6',
    ),
    6 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'asoc_id' => 33000005,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1504,
      'padre_id' => 'pantallas',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 33000010,
      'hijo_id' => 'objetos_pantalla',
      'cascada' => NULL,
      'orden' => '7',
    ),
    7 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'asoc_id' => 33000006,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1505,
      'padre_id' => 'eventos',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 33000011,
      'hijo_id' => 'eventos_pantalla',
      'cascada' => NULL,
      'orden' => '8',
    ),
    8 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'asoc_id' => 33000007,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1504,
      'padre_id' => 'pantallas',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 33000011,
      'hijo_id' => 'eventos_pantalla',
      'cascada' => NULL,
      'orden' => '9',
    ),
  ),
  '_info_dependencias' => 
  array (
    0 => 
    array (
      'identificador' => 'prop_basicas',
      'proyecto' => 'toba_editor',
      'objeto' => 1503,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '1',
      'parametros_b' => '1',
    ),
    1 => 
    array (
      'identificador' => 'pantallas',
      'proyecto' => 'toba_editor',
      'objeto' => 1504,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => 'odt_pantallas',
      'subclase_archivo' => 'db/odt_pantallas.php',
      'fuente' => 'instancia',
      'parametros_a' => '1',
      'parametros_b' => '0',
    ),
    2 => 
    array (
      'identificador' => 'eventos',
      'proyecto' => 'toba_editor',
      'objeto' => 1505,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => 'odt_eventos',
      'subclase_archivo' => 'db/odt_eventos.php',
      'fuente' => 'instancia',
      'parametros_a' => '0',
      'parametros_b' => '0',
    ),
    3 => 
    array (
      'identificador' => 'dependencias',
      'proyecto' => 'toba_editor',
      'objeto' => 1502,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '0',
      'parametros_b' => '0',
    ),
    4 => 
    array (
      'identificador' => 'base',
      'proyecto' => 'toba_editor',
      'objeto' => 1501,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '1',
      'parametros_b' => '1',
    ),
    5 => 
    array (
      'identificador' => 'puntos_control',
      'proyecto' => 'toba_editor',
      'objeto' => 10000033,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    6 => 
    array (
      'identificador' => 'objetos_pantalla',
      'proyecto' => 'toba_editor',
      'objeto' => 33000010,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '0',
      'parametros_b' => '0',
    ),
    7 => 
    array (
      'identificador' => 'eventos_pantalla',
      'proyecto' => 'toba_editor',
      'objeto' => 33000011,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '0',
      'parametros_b' => '0',
    ),
  ),
  '_info_columnas_asoc_rel' => 
  array (
    0 => 
    array (
      'asoc_id' => 1,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 48,
      'hijo_objeto' => 1502,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1501,
      'padre_clave' => 21,
      'col_padre' => 'proyecto',
    ),
    1 => 
    array (
      'asoc_id' => 1,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 49,
      'hijo_objeto' => 1502,
      'col_hija' => 'objeto_consumidor',
      'padre_objeto' => 1501,
      'padre_clave' => 22,
      'col_padre' => 'objeto',
    ),
    2 => 
    array (
      'asoc_id' => 2,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 87,
      'hijo_objeto' => 1505,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1501,
      'padre_clave' => 21,
      'col_padre' => 'proyecto',
    ),
    3 => 
    array (
      'asoc_id' => 2,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 88,
      'hijo_objeto' => 1505,
      'col_hija' => 'objeto',
      'padre_objeto' => 1501,
      'padre_clave' => 22,
      'col_padre' => 'objeto',
    ),
    4 => 
    array (
      'asoc_id' => 3,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 56,
      'hijo_objeto' => 1503,
      'col_hija' => 'objeto_mt_me_proyecto',
      'padre_objeto' => 1501,
      'padre_clave' => 21,
      'col_padre' => 'proyecto',
    ),
    5 => 
    array (
      'asoc_id' => 3,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 57,
      'hijo_objeto' => 1503,
      'col_hija' => 'objeto_mt_me',
      'padre_objeto' => 1501,
      'padre_clave' => 22,
      'col_padre' => 'objeto',
    ),
    6 => 
    array (
      'asoc_id' => 4,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 75,
      'hijo_objeto' => 1504,
      'col_hija' => 'objeto_ci_proyecto',
      'padre_objeto' => 1503,
      'padre_clave' => 56,
      'col_padre' => 'objeto_mt_me_proyecto',
    ),
    7 => 
    array (
      'asoc_id' => 4,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 76,
      'hijo_objeto' => 1504,
      'col_hija' => 'objeto_ci',
      'padre_objeto' => 1503,
      'padre_clave' => 57,
      'col_padre' => 'objeto_mt_me',
    ),
    8 => 
    array (
      'asoc_id' => 10000009,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 10000010,
      'hijo_objeto' => 10000033,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1505,
      'padre_clave' => 87,
      'col_padre' => 'proyecto',
    ),
    9 => 
    array (
      'asoc_id' => 10000009,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 544,
      'hijo_objeto' => 10000033,
      'col_hija' => 'objeto',
      'padre_objeto' => 1505,
      'padre_clave' => 88,
      'col_padre' => 'objeto',
    ),
    10 => 
    array (
      'asoc_id' => 10000009,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 10000012,
      'hijo_objeto' => 10000033,
      'col_hija' => 'evento_id',
      'padre_objeto' => 1505,
      'padre_clave' => 335,
      'col_padre' => 'evento_id',
    ),
    11 => 
    array (
      'asoc_id' => 33000004,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000010,
      'hijo_objeto' => 33000010,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1502,
      'padre_clave' => 48,
      'col_padre' => 'proyecto',
    ),
    12 => 
    array (
      'asoc_id' => 33000004,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000012,
      'hijo_objeto' => 33000010,
      'col_hija' => 'objeto_ci',
      'padre_objeto' => 1502,
      'padre_clave' => 49,
      'col_padre' => 'objeto_consumidor',
    ),
    13 => 
    array (
      'asoc_id' => 33000004,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000014,
      'hijo_objeto' => 33000010,
      'col_hija' => 'dep_id',
      'padre_objeto' => 1502,
      'padre_clave' => 332,
      'col_padre' => 'dep_id',
    ),
    14 => 
    array (
      'asoc_id' => 33000005,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000010,
      'hijo_objeto' => 33000010,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1504,
      'padre_clave' => 75,
      'col_padre' => 'objeto_ci_proyecto',
    ),
    15 => 
    array (
      'asoc_id' => 33000005,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000012,
      'hijo_objeto' => 33000010,
      'col_hija' => 'objeto_ci',
      'padre_objeto' => 1504,
      'padre_clave' => 76,
      'col_padre' => 'objeto_ci',
    ),
    16 => 
    array (
      'asoc_id' => 33000005,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000011,
      'hijo_objeto' => 33000010,
      'col_hija' => 'pantalla',
      'padre_objeto' => 1504,
      'padre_clave' => 77,
      'col_padre' => 'pantalla',
    ),
    17 => 
    array (
      'asoc_id' => 33000006,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000019,
      'hijo_objeto' => 33000011,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1505,
      'padre_clave' => 87,
      'col_padre' => 'proyecto',
    ),
    18 => 
    array (
      'asoc_id' => 33000006,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000018,
      'hijo_objeto' => 33000011,
      'col_hija' => 'evento_id',
      'padre_objeto' => 1505,
      'padre_clave' => 335,
      'col_padre' => 'evento_id',
    ),
    19 => 
    array (
      'asoc_id' => 33000007,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000019,
      'hijo_objeto' => 33000011,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1504,
      'padre_clave' => 75,
      'col_padre' => 'objeto_ci_proyecto',
    ),
    20 => 
    array (
      'asoc_id' => 33000007,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000017,
      'hijo_objeto' => 33000011,
      'col_hija' => 'objeto_ci',
      'padre_objeto' => 1504,
      'padre_clave' => 76,
      'col_padre' => 'objeto_ci',
    ),
    21 => 
    array (
      'asoc_id' => 33000007,
      'proyecto' => 'toba_editor',
      'objeto' => 1507,
      'hijo_clave' => 33000016,
      'hijo_objeto' => 33000011,
      'col_hija' => 'pantalla',
      'padre_objeto' => 1504,
      'padre_clave' => 77,
      'col_padre' => 'pantalla',
    ),
  ),
);
	}

}

?>