<?php

class toba_mc_comp__1000295
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'toba_editor',
    'objeto' => 1000295,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_tabla',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'Asistente - ABMS - datos - base',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba_editor',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2007-07-19 16:34:24',
    'punto_montaje' => 12,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000250',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000250',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'datos_tabla',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => 12,
    'cant_dependencias' => 0,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'tabla' => 'apex_molde_operacion_abms',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => 1,
    'punto_montaje' => 12,
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => 0,
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/componentes/persistencia/toba_ap_tabla_db_s.php',
    'tabla_ext' => NULL,
    'esquema' => NULL,
    'esquema_ext' => NULL,
  ),
  '_info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 655,
      'columna' => 'filtro_comprobar_parametros',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    1 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 657,
      'columna' => 'cuadro_forzar_filtro',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    2 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000168,
      'columna' => 'proyecto',
      'tipo' => 'C',
      'pk' => 1,
      'secuencia' => '',
      'largo' => 255,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    3 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000169,
      'columna' => 'molde',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    4 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000170,
      'columna' => 'tabla',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 255,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => NULL,
    ),
    5 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000171,
      'columna' => 'gen_usa_filtro',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    6 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000172,
      'columna' => 'gen_separar_pantallas',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    7 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000173,
      'columna' => 'cuadro_eof',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 255,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    8 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000174,
      'columna' => 'cuadro_eliminar_filas',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    9 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000175,
      'columna' => 'cuadro_id',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 255,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    10 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000176,
      'columna' => 'cuadro_carga_origen',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 15,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    11 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000177,
      'columna' => 'cuadro_carga_sql',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -5,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    12 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000178,
      'columna' => 'cuadro_carga_php_include',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 255,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    13 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000179,
      'columna' => 'cuadro_carga_php_clase',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 255,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    14 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000180,
      'columna' => 'cuadro_carga_php_metodo',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 255,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    15 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000181,
      'columna' => 'datos_tabla_validacion',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    16 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 1000182,
      'columna' => 'apdb_pre',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => -1,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    17 => 
    array (
      'objeto_proyecto' => 'toba_editor',
      'objeto' => 1000295,
      'col_id' => 33000114,
      'columna' => 'punto_montaje',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
  ),
  '_info_externas' => 
  array (
  ),
  '_info_externas_col' => 
  array (
  ),
  '_info_valores_unicos' => 
  array (
  ),
  '_info_fks' => 
  array (
  ),
);
	}

}

?>