<?php

class toba_mc_comp__1535
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'toba_editor',
    'objeto' => 1535,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_relacion',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'Comp. ei_filtro',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba_editor',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2005-08-28 03:51:37',
    'punto_montaje' => 12,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000251',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_relacion.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000251',
    'clase_icono' => 'objetos/datos_relacion.gif',
    'clase_descripcion_corta' => 'datos_relacion',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => 'ap_relacion_objeto',
    'ap_archivo' => 'db/ap_relacion_objeto.php',
    'ap_punto_montaje' => 12,
    'cant_dependencias' => 5,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'proyecto' => 'toba_editor',
    'objeto' => 1535,
    'debug' => 0,
    'ap' => 3,
    'punto_montaje' => 12,
    'ap_clase' => 'ap_relacion_objeto',
    'ap_archivo' => 'db/ap_relacion_objeto.php',
    'sinc_susp_constraints' => 0,
    'sinc_orden_automatico' => 1,
    'sinc_lock_optimista' => 1,
  ),
  '_info_relaciones' => 
  array (
    0 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'asoc_id' => 12,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1501,
      'padre_id' => 'base',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1000582,
      'hijo_id' => 'prop_basicas',
      'cascada' => 0,
      'orden' => '1',
    ),
    1 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'asoc_id' => 14,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1501,
      'padre_id' => 'base',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1505,
      'hijo_id' => 'eventos',
      'cascada' => 0,
      'orden' => '2',
    ),
    2 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'asoc_id' => 1000017,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1000582,
      'padre_id' => 'prop_basicas',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 1000583,
      'hijo_id' => 'cols',
      'cascada' => NULL,
      'orden' => '4',
    ),
    3 => 
    array (
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'asoc_id' => 10000006,
      'padre_proyecto' => 'toba_editor',
      'padre_objeto' => 1505,
      'padre_id' => 'eventos',
      'hijo_proyecto' => 'toba_editor',
      'hijo_objeto' => 10000033,
      'hijo_id' => 'puntos_control',
      'cascada' => NULL,
      'orden' => '3',
    ),
  ),
  '_info_dependencias' => 
  array (
    0 => 
    array (
      'identificador' => 'prop_basicas',
      'proyecto' => 'toba_editor',
      'objeto' => 1000582,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '1',
      'parametros_b' => '1',
    ),
    1 => 
    array (
      'identificador' => 'eventos',
      'proyecto' => 'toba_editor',
      'objeto' => 1505,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => 'odt_eventos',
      'subclase_archivo' => 'db/odt_eventos.php',
      'fuente' => 'instancia',
      'parametros_a' => '0',
      'parametros_b' => '0',
    ),
    2 => 
    array (
      'identificador' => 'base',
      'proyecto' => 'toba_editor',
      'objeto' => 1501,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '1',
      'parametros_b' => '1',
    ),
    3 => 
    array (
      'identificador' => 'puntos_control',
      'proyecto' => 'toba_editor',
      'objeto' => 10000033,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    4 => 
    array (
      'identificador' => 'cols',
      'proyecto' => 'toba_editor',
      'objeto' => 1000583,
      'clase' => 'toba_datos_tabla',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'instancia',
      'parametros_a' => '1',
      'parametros_b' => '',
    ),
  ),
  '_info_columnas_asoc_rel' => 
  array (
    0 => 
    array (
      'asoc_id' => 12,
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'hijo_clave' => 1000356,
      'hijo_objeto' => 1000582,
      'col_hija' => 'objeto_ei_filtro_proyecto',
      'padre_objeto' => 1501,
      'padre_clave' => 21,
      'col_padre' => 'proyecto',
    ),
    1 => 
    array (
      'asoc_id' => 12,
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'hijo_clave' => 1000357,
      'hijo_objeto' => 1000582,
      'col_hija' => 'objeto_ei_filtro',
      'padre_objeto' => 1501,
      'padre_clave' => 22,
      'col_padre' => 'objeto',
    ),
    2 => 
    array (
      'asoc_id' => 14,
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'hijo_clave' => 87,
      'hijo_objeto' => 1505,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1501,
      'padre_clave' => 21,
      'col_padre' => 'proyecto',
    ),
    3 => 
    array (
      'asoc_id' => 14,
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'hijo_clave' => 88,
      'hijo_objeto' => 1505,
      'col_hija' => 'objeto',
      'padre_objeto' => 1501,
      'padre_clave' => 22,
      'col_padre' => 'objeto',
    ),
    4 => 
    array (
      'asoc_id' => 1000017,
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'hijo_clave' => 1000361,
      'hijo_objeto' => 1000583,
      'col_hija' => 'objeto_ei_filtro_proyecto',
      'padre_objeto' => 1000582,
      'padre_clave' => 1000356,
      'col_padre' => 'objeto_ei_filtro_proyecto',
    ),
    5 => 
    array (
      'asoc_id' => 1000017,
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'hijo_clave' => 1000360,
      'hijo_objeto' => 1000583,
      'col_hija' => 'objeto_ei_filtro',
      'padre_objeto' => 1000582,
      'padre_clave' => 1000357,
      'col_padre' => 'objeto_ei_filtro',
    ),
    6 => 
    array (
      'asoc_id' => 10000006,
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'hijo_clave' => 10000010,
      'hijo_objeto' => 10000033,
      'col_hija' => 'proyecto',
      'padre_objeto' => 1505,
      'padre_clave' => 87,
      'col_padre' => 'proyecto',
    ),
    7 => 
    array (
      'asoc_id' => 10000006,
      'proyecto' => 'toba_editor',
      'objeto' => 1535,
      'hijo_clave' => 10000012,
      'hijo_objeto' => 10000033,
      'col_hija' => 'evento_id',
      'padre_objeto' => 1505,
      'padre_clave' => 335,
      'col_padre' => 'evento_id',
    ),
  ),
);
	}

}

?>