<?

class php_457
{
	static function get_metadatos()
	{
		return array (
  'info' => 
  array (
    'proyecto' => 'toba',
    'objeto' => '457',
    'anterior' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'objeto_cuadro_reg',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'AUDITORIA - Error Login - Detalle',
    'titulo' => 'Error Login',
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2004-07-06 14:41:51',
    'clase_editor_proyecto' => 'toba',
    'clase_editor_item' => '/admin/objetos/editores/cuadro_reg',
    'clase_archivo' => 'nucleo/browser/clases/objeto_cuadro_reg.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '/admin/objetos/editores/cuadro_reg',
    'clase_icono' => 'objetos/cuadro2.gif',
    'clase_descripcion_corta' => 'objeto_cuadro_reg',
    'clase_instanciador_proyecto' => 'toba',
    'clase_instanciador_item' => '/admin/objetos/instanciadores/cuadro_reg',
    'objeto_existe_ayuda' => NULL,
  ),
  'info_cuadro' => 
  array (
    'titulo' => 'Error Login',
    'subtitulo' => NULL,
    'sql' => 'SELECT log_error_login,
momento,
usuario,
clave,
ip,
gravedad,
mensaje,
punto_acceso
FROM apex_log_error_login
%w%',
    'columnas_clave' => 'log_error_login',
    'archivos_callbacks' => NULL,
    'ancho' => '100%',
    'ordenar' => NULL,
    'exportar_xls' => NULL,
    'exportar_pdf' => NULL,
    'paginar' => NULL,
    'tamano_pagina' => NULL,
    'eof_invisible' => NULL,
    'eof_customizado' => NULL,
    'pdf_respetar_paginacion' => NULL,
    'pdf_propiedades' => NULL,
    'asociacion_columnas' => 'log_error_login',
  ),
  'info_cuadro_columna' => 
  array (
    0 => 
    array (
      'orden' => '1',
      'titulo' => 'Err. Log.',
      'estilo' => 'col-num-p1',
      'ancho' => NULL,
      'valor_sql' => 'log_error_login',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    1 => 
    array (
      'orden' => '2',
      'titulo' => 'Momento',
      'estilo' => 'col-num-p1',
      'ancho' => NULL,
      'valor_sql' => 'momento',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    2 => 
    array (
      'orden' => '3',
      'titulo' => 'Usuario',
      'estilo' => 'col-num-p1',
      'ancho' => NULL,
      'valor_sql' => 'usuario',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    3 => 
    array (
      'orden' => '4',
      'titulo' => 'Clave',
      'estilo' => 'col-num-p1',
      'ancho' => NULL,
      'valor_sql' => 'clave',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    4 => 
    array (
      'orden' => '5',
      'titulo' => 'IP',
      'estilo' => 'col-num-p1',
      'ancho' => NULL,
      'valor_sql' => 'ip',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    5 => 
    array (
      'orden' => '6',
      'titulo' => 'Gravedad',
      'estilo' => 'col-num-p1',
      'ancho' => NULL,
      'valor_sql' => 'gravedad',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    6 => 
    array (
      'orden' => '7',
      'titulo' => 'Mensaje',
      'estilo' => 'col-num-p1',
      'ancho' => NULL,
      'valor_sql' => 'mensaje',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    7 => 
    array (
      'orden' => '8',
      'titulo' => 'Punto Acceso',
      'estilo' => 'col-num-p1',
      'ancho' => NULL,
      'valor_sql' => 'punto_acceso',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
  ),
);
	}

}
?>