------------------------------------------------------------
--[1625]--  Prueba relacion 1 ->N  1 -> N 
------------------------------------------------------------
INSERT INTO apex_objeto (proyecto, objeto, anterior, reflexivo, clase_proyecto, clase, subclase, subclase_archivo, objeto_categoria_proyecto, objeto_categoria, nombre, titulo, colapsable, descripcion, fuente_datos_proyecto, fuente_datos, solicitud_registrar, solicitud_obj_obs_tipo, solicitud_obj_observacion, parametro_a, parametro_b, parametro_c, parametro_d, parametro_e, parametro_f, usuario, creacion) VALUES ('toba_testing', '1625', NULL, NULL, 'toba', 'objeto_datos_relacion', NULL, NULL, NULL, NULL, 'Prueba relacion 1 ->N  1 -> N', NULL, NULL, 'En 1 departamento trabajan N empleados, 
En 1 departamento se realizan N tareas asociadas a él.
1 empleado tiene N tareas.', 'toba_testing', 'instancia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-04 03:01:13');
INSERT INTO apex_objeto_datos_rel (proyecto, objeto, debug, clave, ap, ap_clase, ap_archivo, sinc_susp_constraints, sinc_orden_automatico) VALUES ('toba_testing', '1625', '0', NULL, '2', NULL, NULL, '0', '1');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_testing', '1625', '1', 'depto - empleados', 'toba_testing', '1743', 'depto', 'cod_depto', 'toba_testing', '1744', 'empleado', 'depto', NULL, '1');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_testing', '1625', '2', 'empleado - tareas', 'toba_testing', '1744', 'empleado', 'cod_empleado', 'toba_testing', '1745', 'empleado_tareas', 'empleado', NULL, '2');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_testing', '1625', '4', 'depto - tareas depto', 'toba_testing', '1743', 'depto', 'cod_depto', 'toba_testing', '1748', 'depto_tareas', 'depto', NULL, '4');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_testing', '1625', '6', 'tarea - tareas depto', 'toba_testing', '1747', 'tarea', 'cod_tarea', 'toba_testing', '1748', 'depto_tareas', 'tarea', NULL, '5');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_testing', '1625', '19', NULL, 'toba_testing', '1747', 'tarea', 'cod_tarea', 'toba_testing', '1745', 'empleado_tareas', 'tarea', NULL, '3');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_testing', '712', '1625', '1743', 'depto', NULL, NULL, NULL, NULL, '5');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_testing', '716', '1625', '1748', 'depto_tareas', NULL, NULL, NULL, NULL, '1');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_testing', '713', '1625', '1744', 'empleado', NULL, NULL, NULL, NULL, '4');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_testing', '714', '1625', '1745', 'empleado_tareas', NULL, NULL, NULL, NULL, '3');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_testing', '715', '1625', '1747', 'tarea', NULL, NULL, NULL, NULL, '2');
