<?php

class toba_mc_comp__2175
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'toba_usuarios',
    'objeto' => 2175,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_ci',
    'subclase' => 'ci_navegacion_perfiles',
    'subclase_archivo' => 'perfiles/perfil_funcional/ci_navegacion_perfiles.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'Mantenimiento de Perfiles Funcionales',
    'titulo' => 'Perfiles Funcionales',
    'colapsable' => 0,
    'descripcion' => NULL,
    'fuente_proyecto' => NULL,
    'fuente' => NULL,
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2008-02-19 16:37:04',
    'punto_montaje' => 12000004,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000249',
    'clase_archivo' => 'nucleo/componentes/interface/toba_ci.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000249',
    'clase_icono' => 'objetos/multi_etapa.gif',
    'clase_descripcion_corta' => 'ci',
    'clase_instanciador_proyecto' => 'toba_editor',
    'clase_instanciador_item' => '1642',
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => NULL,
    'cant_dependencias' => 6,
    'posicion_botonera' => 'ambos',
  ),
  '_info_eventos' => 
  array (
    0 => 
    array (
      'evento_id' => 30000105,
      'identificador' => 'ver_grafico',
      'etiqueta' => 'Ver Esquema',
      'maneja_datos' => 0,
      'sobre_fila' => NULL,
      'confirmacion' => NULL,
      'estilo' => 'ei-boton-izq',
      'imagen_recurso_origen' => 'apex',
      'imagen' => 'objetos/esquema.gif',
      'en_botonera' => 1,
      'ayuda' => NULL,
      'ci_predep' => NULL,
      'implicito' => 0,
      'defecto' => 0,
      'grupo' => NULL,
      'accion' => NULL,
      'accion_imphtml_debug' => 0,
      'accion_vinculo_carpeta' => NULL,
      'accion_vinculo_item' => NULL,
      'accion_vinculo_objeto' => NULL,
      'accion_vinculo_popup' => 0,
      'accion_vinculo_popup_param' => NULL,
      'accion_vinculo_celda' => NULL,
      'accion_vinculo_target' => NULL,
      'accion_vinculo_servicio' => NULL,
      'es_seleccion_multiple' => 0,
      'es_autovinculo' => 0,
    ),
    1 => 
    array (
      'evento_id' => 975,
      'identificador' => 'agregar',
      'etiqueta' => 'Agregar',
      'maneja_datos' => 0,
      'sobre_fila' => NULL,
      'confirmacion' => NULL,
      'estilo' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => 'nucleo/agregar.gif',
      'en_botonera' => 1,
      'ayuda' => NULL,
      'ci_predep' => NULL,
      'implicito' => 0,
      'defecto' => 0,
      'grupo' => NULL,
      'accion' => NULL,
      'accion_imphtml_debug' => 0,
      'accion_vinculo_carpeta' => NULL,
      'accion_vinculo_item' => NULL,
      'accion_vinculo_objeto' => NULL,
      'accion_vinculo_popup' => 0,
      'accion_vinculo_popup_param' => NULL,
      'accion_vinculo_celda' => NULL,
      'accion_vinculo_target' => NULL,
      'accion_vinculo_servicio' => NULL,
      'es_seleccion_multiple' => 0,
      'es_autovinculo' => 0,
    ),
    2 => 
    array (
      'evento_id' => 946,
      'identificador' => 'volver',
      'etiqueta' => 'Volver',
      'maneja_datos' => 0,
      'sobre_fila' => NULL,
      'confirmacion' => NULL,
      'estilo' => 'ei-boton-izq',
      'imagen_recurso_origen' => 'apex',
      'imagen' => 'volver.png',
      'en_botonera' => 1,
      'ayuda' => NULL,
      'ci_predep' => NULL,
      'implicito' => 0,
      'defecto' => 0,
      'grupo' => NULL,
      'accion' => NULL,
      'accion_imphtml_debug' => 0,
      'accion_vinculo_carpeta' => NULL,
      'accion_vinculo_item' => NULL,
      'accion_vinculo_objeto' => NULL,
      'accion_vinculo_popup' => 0,
      'accion_vinculo_popup_param' => NULL,
      'accion_vinculo_celda' => NULL,
      'accion_vinculo_target' => NULL,
      'accion_vinculo_servicio' => NULL,
      'es_seleccion_multiple' => 0,
      'es_autovinculo' => 0,
    ),
    3 => 
    array (
      'evento_id' => 974,
      'identificador' => 'eliminar',
      'etiqueta' => 'Eliminar',
      'maneja_datos' => 0,
      'sobre_fila' => NULL,
      'confirmacion' => 'Confirme la eliminación del Perfil Funcional seleccionado',
      'estilo' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => 'borrar.gif',
      'en_botonera' => 1,
      'ayuda' => NULL,
      'ci_predep' => NULL,
      'implicito' => 0,
      'defecto' => 0,
      'grupo' => NULL,
      'accion' => NULL,
      'accion_imphtml_debug' => 0,
      'accion_vinculo_carpeta' => NULL,
      'accion_vinculo_item' => NULL,
      'accion_vinculo_objeto' => NULL,
      'accion_vinculo_popup' => 0,
      'accion_vinculo_popup_param' => NULL,
      'accion_vinculo_celda' => NULL,
      'accion_vinculo_target' => NULL,
      'accion_vinculo_servicio' => NULL,
      'es_seleccion_multiple' => 0,
      'es_autovinculo' => 0,
    ),
    4 => 
    array (
      'evento_id' => 970,
      'identificador' => 'guardar',
      'etiqueta' => 'Guardar',
      'maneja_datos' => 1,
      'sobre_fila' => NULL,
      'confirmacion' => NULL,
      'estilo' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => 'guardar.gif',
      'en_botonera' => 1,
      'ayuda' => NULL,
      'ci_predep' => NULL,
      'implicito' => 0,
      'defecto' => 0,
      'grupo' => NULL,
      'accion' => NULL,
      'accion_imphtml_debug' => 0,
      'accion_vinculo_carpeta' => NULL,
      'accion_vinculo_item' => NULL,
      'accion_vinculo_objeto' => NULL,
      'accion_vinculo_popup' => 0,
      'accion_vinculo_popup_param' => NULL,
      'accion_vinculo_celda' => NULL,
      'accion_vinculo_target' => NULL,
      'accion_vinculo_servicio' => NULL,
      'es_seleccion_multiple' => 0,
      'es_autovinculo' => 0,
    ),
  ),
  '_info_puntos_control' => 
  array (
  ),
  '_info_ci' => 
  array (
    'ev_procesar_etiq' => NULL,
    'ev_cancelar_etiq' => NULL,
    'objetos' => NULL,
    'ancho' => '550px',
    'alto' => '300px',
    'posicion_botonera' => 'ambos',
    'tipo_navegacion' => NULL,
    'con_toc' => 0,
    'botonera_barra_item' => 0,
  ),
  '_info_ci_me_pantalla' => 
  array (
    0 => 
    array (
      'pantalla' => 1130,
      'identificador' => 'seleccion_perfil',
      'etiqueta' => 'Seleccionar',
      'descripcion' => NULL,
      'tip' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => NULL,
      'objetos' => NULL,
      'eventos' => NULL,
      'orden' => 1,
      'punto_montaje' => 12000004,
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'template' => NULL,
      'template_impresion' => NULL,
    ),
    1 => 
    array (
      'pantalla' => 1131,
      'identificador' => 'edicion_perfil',
      'etiqueta' => 'Editar',
      'descripcion' => NULL,
      'tip' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => NULL,
      'objetos' => NULL,
      'eventos' => NULL,
      'orden' => 2,
      'punto_montaje' => 12000004,
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'template' => NULL,
      'template_impresion' => NULL,
    ),
  ),
  '_info_obj_pantalla' => 
  array (
    0 => 
    array (
      'pantalla' => 1130,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'dep_id' => 1106,
      'orden' => 1,
      'identificador_pantalla' => 'seleccion_perfil',
      'identificador_dep' => 'filtro_proyectos',
    ),
    1 => 
    array (
      'pantalla' => 1131,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'dep_id' => 1109,
      'orden' => 1,
      'identificador_pantalla' => 'edicion_perfil',
      'identificador_dep' => 'form_datos_perfil',
    ),
    2 => 
    array (
      'pantalla' => 1130,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'dep_id' => 1107,
      'orden' => 2,
      'identificador_pantalla' => 'seleccion_perfil',
      'identificador_dep' => 'cuadro_grupos_acceso',
    ),
    3 => 
    array (
      'pantalla' => 1131,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'dep_id' => 1105,
      'orden' => 2,
      'identificador_pantalla' => 'edicion_perfil',
      'identificador_dep' => 'editor_perfiles',
    ),
    4 => 
    array (
      'pantalla' => 1130,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'dep_id' => 30000055,
      'orden' => 3,
      'identificador_pantalla' => 'seleccion_perfil',
      'identificador_dep' => 'esquema',
    ),
  ),
  '_info_evt_pantalla' => 
  array (
    0 => 
    array (
      'pantalla' => 1130,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'evento_id' => 975,
      'identificador_pantalla' => 'seleccion_perfil',
      'identificador_evento' => 'agregar',
    ),
    1 => 
    array (
      'pantalla' => 1130,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'evento_id' => 30000105,
      'identificador_pantalla' => 'seleccion_perfil',
      'identificador_evento' => 'ver_grafico',
    ),
    2 => 
    array (
      'pantalla' => 1131,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'evento_id' => 946,
      'identificador_pantalla' => 'edicion_perfil',
      'identificador_evento' => 'volver',
    ),
    3 => 
    array (
      'pantalla' => 1131,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'evento_id' => 970,
      'identificador_pantalla' => 'edicion_perfil',
      'identificador_evento' => 'guardar',
    ),
    4 => 
    array (
      'pantalla' => 1131,
      'proyecto' => 'toba_usuarios',
      'objeto_ci' => 2175,
      'evento_id' => 974,
      'identificador_pantalla' => 'edicion_perfil',
      'identificador_evento' => 'eliminar',
    ),
  ),
  '_info_dependencias' => 
  array (
    0 => 
    array (
      'identificador' => 'cuadro_grupos_acceso',
      'proyecto' => 'toba_usuarios',
      'objeto' => 2200,
      'clase' => 'toba_ei_cuadro',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_cuadro.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => NULL,
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    1 => 
    array (
      'identificador' => 'datos',
      'proyecto' => 'toba_usuarios',
      'objeto' => 2202,
      'clase' => 'toba_datos_relacion',
      'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_relacion.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'toba_usuarios',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    2 => 
    array (
      'identificador' => 'editor_perfiles',
      'proyecto' => 'toba_usuarios',
      'objeto' => 2198,
      'clase' => 'toba_ci',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ci.php',
      'subclase' => 'ci_editor_perfiles',
      'subclase_archivo' => 'perfiles/perfil_funcional/ci_editor_perfiles.php',
      'fuente' => NULL,
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    3 => 
    array (
      'identificador' => 'esquema',
      'proyecto' => 'toba_usuarios',
      'objeto' => 30000109,
      'clase' => 'toba_ei_esquema',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_esquema.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => NULL,
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    4 => 
    array (
      'identificador' => 'filtro_proyectos',
      'proyecto' => 'toba_usuarios',
      'objeto' => 2199,
      'clase' => 'toba_ei_formulario',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_formulario.php',
      'subclase' => 'form_proyecto',
      'subclase_archivo' => 'perfiles/form_proyecto.php',
      'fuente' => 'toba_usuarios',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    5 => 
    array (
      'identificador' => 'form_datos_perfil',
      'proyecto' => 'toba_usuarios',
      'objeto' => 2201,
      'clase' => 'toba_ei_formulario',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_formulario.php',
      'subclase' => 'ei_form_datos_perfil',
      'subclase_archivo' => 'perfiles/perfil_funcional/ei_form_datos_perfil.php',
      'fuente' => 'toba_usuarios',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
  ),
);
	}

}

?>