<?

class php_1530
{
	static function get_metadatos()
	{
		return array (
  'info' => 
  array (
    'proyecto' => 'toba',
    'objeto' => '1530',
    'anterior' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'objeto_datos_tabla',
    'subclase' => 'odt_formulario_efs',
    'subclase_archivo' => 'admin/db/odt_formulario_efs.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'OBJETO - EI formulario EF',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2005-08-28 03:20:29',
    'clase_editor_proyecto' => 'toba',
    'clase_editor_item' => '/admin/objetos_toba/editores/db_registros',
    'clase_archivo' => 'nucleo/persistencia/objeto_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '/admin/objetos_toba/editores/db_registros',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'Objeto DATOS - TABLA',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
  ),
  'info_estructura' => 
  array (
    'tabla' => 'apex_objeto_ei_formulario_ef',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => '1',
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => '0',
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/persistencia/ap_tabla_db_s.php',
  ),
  'info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '207',
      'columna' => 'objeto_ei_formulario_proyecto',
      'tipo' => 'C',
      'pk' => '1',
      'secuencia' => NULL,
      'largo' => '15',
      'no_nulo' => NULL,
      'no_nulo_db' => '1',
      'externa' => NULL,
    ),
    1 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '208',
      'columna' => 'objeto_ei_formulario',
      'tipo' => 'E',
      'pk' => '1',
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => '1',
      'externa' => NULL,
    ),
    2 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '209',
      'columna' => 'objeto_ei_formulario_fila',
      'tipo' => 'E',
      'pk' => '1',
      'secuencia' => 'apex_obj_ei_form_fila_seq',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => '1',
      'externa' => NULL,
    ),
    3 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '210',
      'columna' => 'identificador',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '30',
      'no_nulo' => NULL,
      'no_nulo_db' => '1',
      'externa' => NULL,
    ),
    4 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '211',
      'columna' => 'elemento_formulario',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '30',
      'no_nulo' => NULL,
      'no_nulo_db' => '1',
      'externa' => NULL,
    ),
    5 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '212',
      'columna' => 'columnas',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '255',
      'no_nulo' => NULL,
      'no_nulo_db' => '1',
      'externa' => NULL,
    ),
    6 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '213',
      'columna' => 'obligatorio',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    7 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '214',
      'columna' => 'inicializacion',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '-1',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    8 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '215',
      'columna' => 'orden',
      'tipo' => NULL,
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => '1',
      'externa' => NULL,
    ),
    9 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '216',
      'columna' => 'etiqueta',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '80',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    10 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '217',
      'columna' => 'descripcion',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '-1',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    11 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '218',
      'columna' => 'colapsado',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    12 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '219',
      'columna' => 'desactivado',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    13 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '220',
      'columna' => 'estilo',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    14 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '221',
      'columna' => 'total',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
    15 => 
    array (
      'objeto_proyecto' => 'toba',
      'objeto' => '1530',
      'col_id' => '362',
      'columna' => 'etiqueta_estilo',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => '80',
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
    ),
  ),
);
	}

}
?>