<?

class php_618
{
	static function get_metadatos()
	{
		return array (
  'info' => 
  array (
    'proyecto' => 'toba',
    'objeto' => '618',
    'anterior' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'objeto_cuadro',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'TRABAJO - Notas grales. objetos',
    'titulo' => 'Notas generales - Objetos',
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => NULL,
    'clase_editor_proyecto' => 'toba',
    'clase_editor_item' => '/admin/objetos/editores/cuadro',
    'clase_archivo' => 'nucleo/browser/clases/objeto_cuadro.php',
    'clase_vinculos' => '1',
    'clase_editor' => '/admin/objetos/editores/cuadro',
    'clase_icono' => 'objetos/cuadro.gif',
    'clase_descripcion_corta' => 'CUADRO',
    'clase_instanciador_proyecto' => 'toba',
    'clase_instanciador_item' => '/admin/objetos/instanciadores/cuadro',
    'objeto_existe_ayuda' => NULL,
  ),
  'info_cuadro' => 
  array (
    'titulo' => NULL,
    'subtitulo' => NULL,
    'sql' => 'SELECT 
objeto_nota,
nota_tipo,
objeto,
usuario_origen,
titulo,
creacion
FROM apex_objeto_nota',
    'columnas_clave' => 'objeto_nota',
    'archivos_callbacks' => NULL,
    'ancho' => '90%',
    'ordenar' => '1',
    'exportar_xls' => NULL,
    'exportar_pdf' => NULL,
    'paginar' => '1',
    'tamano_pagina' => '25',
    'eof_invisible' => '1',
    'eof_customizado' => NULL,
    'pdf_respetar_paginacion' => NULL,
    'pdf_propiedades' => '',
    'asociacion_columnas' => NULL,
  ),
  'info_cuadro_columna' => 
  array (
    0 => 
    array (
      'orden' => '0',
      'titulo' => 'Nota',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'objeto_nota',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    1 => 
    array (
      'orden' => '2',
      'titulo' => 'Tipo',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'nota_tipo',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    2 => 
    array (
      'orden' => '3',
      'titulo' => 'Objeto',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'objeto',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    3 => 
    array (
      'orden' => '4',
      'titulo' => 'Emisor',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'usuario_origen',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    4 => 
    array (
      'orden' => '5',
      'titulo' => 'Título',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'titulo',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
    5 => 
    array (
      'orden' => '6',
      'titulo' => 'Fecha',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'creacion',
      'valor_sql_formato' => 'fecha',
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => '1',
      'mostrar_pdf' => '1',
      'pdf_propiedades' => '',
      'total' => NULL,
    ),
  ),
);
	}

}
?>