<?

class php_459
{
	static function get_metadatos()
	{
		return array (
  'info' => 
  array (
    'proyecto' => 'toba',
    'objeto' => '459',
    'anterior' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'objeto_cuadro',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'AUDITORIA - Log IP Rechazada',
    'titulo' => 'Log IP Rechazada',
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'toba',
    'fuente' => 'instancia',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2004-07-06 16:01:31',
    'clase_editor_proyecto' => 'toba',
    'clase_editor_item' => '/admin/objetos/editores/cuadro',
    'clase_archivo' => 'nucleo/browser/clases/objeto_cuadro.php',
    'clase_vinculos' => '1',
    'clase_editor' => '/admin/objetos/editores/cuadro',
    'clase_icono' => 'objetos/cuadro.gif',
    'clase_descripcion_corta' => 'CUADRO',
    'clase_instanciador_proyecto' => 'toba',
    'clase_instanciador_item' => '/admin/objetos/instanciadores/cuadro',
    'objeto_existe_ayuda' => NULL,
  ),
  'info_cuadro' => 
  array (
    'titulo' => 'Log IP Rechazada',
    'subtitulo' => NULL,
    'sql' => 'SELECT ip, momento FROM apex_log_ip_rechazada 
%w%',
    'columnas_clave' => 'ip',
    'archivos_callbacks' => NULL,
    'ancho' => '100%',
    'ordenar' => NULL,
    'exportar_xls' => NULL,
    'exportar_pdf' => NULL,
    'paginar' => NULL,
    'tamano_pagina' => NULL,
    'eof_invisible' => NULL,
    'eof_customizado' => NULL,
    'pdf_respetar_paginacion' => NULL,
    'pdf_propiedades' => NULL,
    'asociacion_columnas' => NULL,
  ),
  'info_cuadro_columna' => 
  array (
    0 => 
    array (
      'orden' => '1',
      'titulo' => 'IP',
      'estilo' => 'col-num-p1',
      'ancho' => NULL,
      'valor_sql' => 'ip',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    1 => 
    array (
      'orden' => '2',
      'titulo' => 'Momento',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'momento',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => NULL,
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
    2 => 
    array (
      'orden' => '3',
      'titulo' => 'Desbloquear',
      'estilo' => 'col-tex-p1',
      'ancho' => NULL,
      'valor_sql' => 'ip',
      'valor_sql_formato' => NULL,
      'valor_fijo' => NULL,
      'valor_proceso' => NULL,
      'valor_proceso_parametros' => NULL,
      'vinculo_indice' => 'ip',
      'par_dimension_proyecto' => NULL,
      'par_dimension' => NULL,
      'par_tabla' => NULL,
      'par_columna' => NULL,
      'no_ordenar' => NULL,
      'mostrar_xls' => NULL,
      'mostrar_pdf' => NULL,
      'pdf_propiedades' => NULL,
      'total' => NULL,
    ),
  ),
);
	}

}
?>