------------------------------------------------------------
--[1536]--  OBJETO - EI formulario ML 
------------------------------------------------------------
INSERT INTO apex_objeto (proyecto, objeto, anterior, reflexivo, clase_proyecto, clase, subclase, subclase_archivo, objeto_categoria_proyecto, objeto_categoria, nombre, titulo, colapsable, descripcion, fuente_datos_proyecto, fuente_datos, solicitud_registrar, solicitud_obj_obs_tipo, solicitud_obj_observacion, parametro_a, parametro_b, parametro_c, parametro_d, parametro_e, parametro_f, usuario, creacion) VALUES ('toba_editor', '1536', NULL, NULL, 'toba', 'objeto_datos_relacion', NULL, NULL, NULL, NULL, 'OBJETO - EI formulario ML', NULL, NULL, NULL, 'toba_editor', 'instancia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-08-28 03:53:29');
INSERT INTO apex_objeto_datos_rel (proyecto, objeto, debug, clave, ap, ap_clase, ap_archivo, sinc_susp_constraints, sinc_orden_automatico) VALUES ('toba_editor', '1536', '0', NULL, '3', 'ap_relacion_objeto', 'db/ap_relacion_objeto.php', '0', '1');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_editor', '1536', '15', 'base -> prop_basicas', 'toba_editor', '1501', 'base', 'proyecto,objeto', 'toba_editor', '1529', 'prop_basicas', 'objeto_ut_formulario_proyecto,objeto_ut_formulario', '0', '1');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_editor', '1536', '16', 'base -> efs', 'toba_editor', '1529', 'prop_basicas', 'objeto_ut_formulario_proyecto,objeto_ut_formulario', 'toba_editor', '1530', 'efs', 'objeto_ei_formulario_proyecto,objeto_ei_formulario', '0', '2');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_editor', '1536', '17', 'base -> eventos', 'toba_editor', '1501', 'base', 'proyecto,objeto', 'toba_editor', '1505', 'eventos', 'proyecto,objeto', '0', '3');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_editor', '1536', '10000008', NULL, 'toba_editor', '1505', 'eventos', 'proyecto,evento_id', 'toba_editor', '10000033', 'puntos_control', 'proyecto,evento_id', NULL, '4');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '114', '1536', '1501', 'base', '1', '1', NULL, NULL, '4');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '115', '1536', '1530', 'efs', '1', '0', NULL, NULL, '3');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '116', '1536', '1505', 'eventos', '0', '0', NULL, NULL, '2');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '117', '1536', '1529', 'prop_basicas', '1', '1', NULL, NULL, '1');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '10000052', '1536', '10000033', 'puntos_control', NULL, NULL, NULL, NULL, '5');
