------------------------------------------------------------
--[1531]--  OBJETO - EI cuadro 
------------------------------------------------------------
INSERT INTO apex_objeto (proyecto, objeto, anterior, reflexivo, clase_proyecto, clase, subclase, subclase_archivo, objeto_categoria_proyecto, objeto_categoria, nombre, titulo, colapsable, descripcion, fuente_datos_proyecto, fuente_datos, solicitud_registrar, solicitud_obj_obs_tipo, solicitud_obj_observacion, parametro_a, parametro_b, parametro_c, parametro_d, parametro_e, parametro_f, usuario, creacion) VALUES ('toba_editor', '1531', NULL, NULL, 'toba', 'objeto_datos_relacion', 'odr_ei_cuadro', 'db/odr_ei_cuadro.php', NULL, NULL, 'OBJETO - EI cuadro', NULL, NULL, NULL, 'toba_editor', 'instancia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-08-28 03:33:09');
INSERT INTO apex_objeto_datos_rel (proyecto, objeto, debug, clave, ap, ap_clase, ap_archivo, sinc_susp_constraints, sinc_orden_automatico) VALUES ('toba_editor', '1531', '0', NULL, '3', 'ap_relacion_objeto', 'db/ap_relacion_objeto.php', '0', '1');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_editor', '1531', '1', 'base -> cuadro', 'toba_editor', '1501', 'base', 'proyecto,objeto', 'toba_editor', '1523', 'prop_basicas', 'objeto_cuadro_proyecto,objeto_cuadro', '0', '1');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_editor', '1531', '2', 'base -> columna', 'toba_editor', '1523', 'prop_basicas', 'objeto_cuadro_proyecto,objeto_cuadro', 'toba_editor', '1524', 'columnas', 'objeto_cuadro_proyecto,objeto_cuadro', '0', '2');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_editor', '1531', '3', 'base -> eventos', 'toba_editor', '1501', 'base', 'proyecto,objeto', 'toba_editor', '1505', 'eventos', 'proyecto,objeto', '0', '3');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_editor', '1531', '5', 'base -> corte', 'toba_editor', '1523', 'prop_basicas', 'objeto_cuadro_proyecto,objeto_cuadro', 'toba_editor', '1612', 'cortes', 'objeto_cuadro_proyecto,objeto_cuadro', NULL, '4');
INSERT INTO apex_objeto_datos_rel_asoc (proyecto, objeto, asoc_id, identificador, padre_proyecto, padre_objeto, padre_id, padre_clave, hijo_proyecto, hijo_objeto, hijo_id, hijo_clave, cascada, orden) VALUES ('toba_editor', '1531', '10000003', NULL, 'toba_editor', '1505', 'eventos', 'proyecto,evento_id', 'toba_editor', '10000033', 'puntos_control', 'proyecto,evento_id', NULL, '5');
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '94', '1531', '1501', 'base', '1', '1', NULL, NULL, NULL);
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '95', '1531', '1524', 'columnas', '1', '0', NULL, NULL, NULL);
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '96', '1531', '1612', 'cortes', '0', '0', NULL, NULL, NULL);
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '97', '1531', '1505', 'eventos', '0', '0', NULL, NULL, NULL);
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '98', '1531', '1523', 'prop_basicas', '1', '1', NULL, NULL, NULL);
INSERT INTO apex_objeto_dependencias (proyecto, dep_id, objeto_consumidor, objeto_proveedor, identificador, parametros_a, parametros_b, parametros_c, inicializar, orden) VALUES ('toba_editor', '10000039', '1531', '10000033', 'puntos_control', '', '', NULL, NULL, NULL);
