BEGIN;
-- Drop index bindings from system tables
DROP OPERATOR CLASS gist_geometry_ops USING gist CASCADE;
-- Drop all aggregates.
DROP AGGREGATE extent ( geometry );
DROP AGGREGATE memcollect ( geometry );
DROP AGGREGATE collect ( geometry );
DROP AGGREGATE MemGeomUnion ( geometry );
DROP AGGREGATE GeomUnion ( geometry );
-- Drop all operators.
DROP OPERATOR <<  (geometry,geometry) CASCADE;
DROP OPERATOR &<  (geometry,geometry) CASCADE;
DROP OPERATOR &&  (geometry,geometry) CASCADE;
DROP OPERATOR &>  (geometry,geometry) CASCADE;
DROP OPERATOR >>  (geometry,geometry) CASCADE;
DROP OPERATOR ~=  (geometry,geometry) CASCADE;
DROP OPERATOR @  (geometry,geometry) CASCADE;
DROP OPERATOR ~  (geometry,geometry) CASCADE;
DROP OPERATOR <  (geometry,geometry) CASCADE;
DROP OPERATOR <=  (geometry,geometry) CASCADE;
DROP OPERATOR =  (geometry,geometry) CASCADE;
DROP OPERATOR >=  (geometry,geometry) CASCADE;
DROP OPERATOR >  (geometry,geometry) CASCADE;
-- Drop all casts.
DROP CAST ( geometry AS box3d );
DROP CAST ( geometry AS box );
DROP CAST ( box3d AS geometry );
DROP CAST ( text AS geometry);
DROP CAST ( wkb AS bytea );
DROP CAST ( box3d AS box );
DROP CAST ( geometry AS text );
-- Drop all functions.
DROP FUNCTION postgis_gist_sel  (internal, oid, internal, int4) CASCADE;
DROP FUNCTION postgis_version () CASCADE;
DROP FUNCTION postgis_lib_version () CASCADE;
DROP FUNCTION postgis_geos_version () CASCADE;
DROP FUNCTION postgis_proj_version () CASCADE;
DROP FUNCTION postgis_scripts_released () CASCADE;
DROP FUNCTION postgis_uses_stats () CASCADE;
DROP FUNCTION postgis_full_version () CASCADE;
DROP FUNCTION find_srid (varchar,varchar,varchar) CASCADE;
DROP FUNCTION get_proj4_from_srid (integer) CASCADE;
DROP FUNCTION rename_geometry_table_constraints () CASCADE;
DROP FUNCTION fix_geometry_columns () CASCADE;
DROP FUNCTION probe_geometry_columns () CASCADE;
DROP FUNCTION find_extent (text,text,text) CASCADE;
DROP FUNCTION find_extent (text,text) CASCADE;
DROP FUNCTION transform_geometry (geometry,text,text,int) CASCADE;
DROP FUNCTION transform (geometry,integer) CASCADE;
DROP FUNCTION srid (chip) CASCADE;
DROP FUNCTION height (chip) CASCADE;
DROP FUNCTION factor (chip) CASCADE;
DROP FUNCTION width (chip) CASCADE;
DROP FUNCTION datatype (chip) CASCADE;
DROP FUNCTION compression (chip) CASCADE;
DROP FUNCTION setSRID (chip,int4) CASCADE;
DROP FUNCTION setfactor (chip,float4) CASCADE;
DROP FUNCTION geometry (CHIP) CASCADE;
DROP FUNCTION box3d (geometry) CASCADE;
DROP FUNCTION box (geometry) CASCADE;
DROP FUNCTION geometry (box3d) CASCADE;
DROP FUNCTION geometry (text) CASCADE;
DROP FUNCTION expand (box3d,float8) CASCADE;
DROP FUNCTION expand (geometry,float8) CASCADE;
DROP FUNCTION asbinary (geometry) CASCADE;
DROP FUNCTION asbinary (geometry,TEXT) CASCADE;
DROP FUNCTION bytea (wkb) CASCADE;
DROP FUNCTION geometry (wkb) CASCADE;
DROP FUNCTION GeomFromWKB (wkb) CASCADE;
DROP FUNCTION GeomFromWKB (wkb,int) CASCADE;
DROP FUNCTION PointFromWKB (wkb,int) CASCADE;
DROP FUNCTION PointFromWKB (wkb) CASCADE;
DROP FUNCTION LineFromWKB (wkb,int) CASCADE;
DROP FUNCTION LineFromWKB (wkb) CASCADE;
DROP FUNCTION LinestringFromWKB (wkb,int) CASCADE;
DROP FUNCTION LinestringFromWKB (wkb) CASCADE;
DROP FUNCTION PolyFromWKB (wkb,int) CASCADE;
DROP FUNCTION PolyFromWKB (wkb) CASCADE;
DROP FUNCTION PolygonFromWKB (wkb,int) CASCADE;
DROP FUNCTION PolygonFromWKB (wkb) CASCADE;
DROP FUNCTION MPointFromWKB (wkb,int) CASCADE;
DROP FUNCTION MPointFromWKB (wkb) CASCADE;
DROP FUNCTION MultiPointFromWKB (wkb,int) CASCADE;
DROP FUNCTION MultiPointFromWKB (wkb) CASCADE;
DROP FUNCTION MultiLineFromWKB (wkb,int) CASCADE;
DROP FUNCTION MultiLineFromWKB (wkb) CASCADE;
DROP FUNCTION MLineFromWKB (wkb,int) CASCADE;
DROP FUNCTION MLineFromWKB (wkb) CASCADE;
DROP FUNCTION MPolyFromWKB (wkb,int) CASCADE;
DROP FUNCTION MPolyFromWKB (wkb) CASCADE;
DROP FUNCTION MultiPolyFromWKB (wkb,int) CASCADE;
DROP FUNCTION MultiPolyFromWKB (wkb) CASCADE;
DROP FUNCTION GeomCollFromWKB (wkb,int) CASCADE;
DROP FUNCTION GeomCollFromWKB (wkb) CASCADE;
DROP FUNCTION npoints (geometry) CASCADE;
DROP FUNCTION nrings (geometry) CASCADE;
DROP FUNCTION mem_size (geometry) CASCADE;
DROP FUNCTION summary (geometry) CASCADE;
DROP FUNCTION translate (geometry,float8,float8,float8) CASCADE;
DROP FUNCTION dimension (geometry) CASCADE;
DROP FUNCTION geometrytype (geometry) CASCADE;
DROP FUNCTION envelope (geometry) CASCADE;
DROP FUNCTION x (geometry) CASCADE;
DROP FUNCTION y (geometry) CASCADE;
DROP FUNCTION z (geometry) CASCADE;
DROP FUNCTION numpoints (geometry) CASCADE;
DROP FUNCTION pointn (geometry,integer) CASCADE;
DROP FUNCTION exteriorring (geometry) CASCADE;
DROP FUNCTION numinteriorrings (geometry) CASCADE;
DROP FUNCTION interiorringn (geometry,integer) CASCADE;
DROP FUNCTION numgeometries (geometry) CASCADE;
DROP FUNCTION geometryn (geometry,integer) CASCADE;
DROP FUNCTION max_distance (geometry,geometry) CASCADE;
DROP FUNCTION optimistic_overlap (geometry,geometry,FLOAT8) CASCADE;
DROP FUNCTION segmentize (geometry,FLOAT8) CASCADE;
DROP FUNCTION distance (geometry,geometry) CASCADE;
DROP FUNCTION astext (geometry) CASCADE;
DROP FUNCTION srid (geometry) CASCADE;
DROP FUNCTION geometryfromtext (geometry,int4) CASCADE;
DROP FUNCTION geometryfromtext (geometry) CASCADE;
DROP FUNCTION geomfromtext (geometry,int4) CASCADE;
DROP FUNCTION geomfromtext (geometry) CASCADE;
DROP FUNCTION polyfromtext (geometry,int4) CASCADE;
DROP FUNCTION polygonfromtext (geometry,int4) CASCADE;
DROP FUNCTION polygonfromtext (geometry) CASCADE;
DROP FUNCTION mpolyfromtext (geometry,int4) CASCADE;
DROP FUNCTION linefromtext (geometry,int4) CASCADE;
DROP FUNCTION mlinefromtext (geometry,int4) CASCADE;
DROP FUNCTION multilinestringfromtext (geometry,int4) CASCADE;
DROP FUNCTION multilinestringfromtext (geometry) CASCADE;
DROP FUNCTION pointfromtext (geometry,int4) CASCADE;
DROP FUNCTION mpointfromtext (geometry,int4) CASCADE;
DROP FUNCTION multipointfromtext (geometry,int4) CASCADE;
DROP FUNCTION multipointfromtext (geometry) CASCADE;
DROP FUNCTION geomcollfromtext (geometry,int4) CASCADE;
DROP FUNCTION setSRID (geometry,int4) CASCADE;
DROP FUNCTION polyfromtext (geometry) CASCADE;
DROP FUNCTION mpolyfromtext (geometry) CASCADE;
DROP FUNCTION multipolygonfromtext (geometry) CASCADE;
DROP FUNCTION multipolygonfromtext (geometry,int) CASCADE;
DROP FUNCTION linefromtext (geometry) CASCADE;
DROP FUNCTION linestringfromtext (geometry) CASCADE;
DROP FUNCTION linestringfromtext (geometry,int) CASCADE;
DROP FUNCTION mlinefromtext (geometry) CASCADE;
DROP FUNCTION pointfromtext (geometry) CASCADE;
DROP FUNCTION mpointfromtext (geometry) CASCADE;
DROP FUNCTION geomcollfromtext (geometry) CASCADE;
DROP FUNCTION isempty (geometry) CASCADE;
DROP FUNCTION issimple (geometry) CASCADE;
DROP FUNCTION equals (geometry,geometry) CASCADE;
DROP FUNCTION length_spheroid (geometry,spheroid) CASCADE;
DROP FUNCTION length3d_spheroid (geometry,spheroid) CASCADE;
DROP FUNCTION distance_spheroid (geometry,geometry,spheroid) CASCADE;
DROP FUNCTION multi (geometry) CASCADE;
DROP FUNCTION length3d (geometry) CASCADE;
DROP FUNCTION length (geometry) CASCADE;
DROP FUNCTION area2d (geometry) CASCADE;
DROP FUNCTION area (geometry) CASCADE;
DROP FUNCTION perimeter3d (geometry) CASCADE;
DROP FUNCTION perimeter (geometry) CASCADE;
DROP FUNCTION startpoint (geometry) CASCADE;
DROP FUNCTION endpoint (geometry) CASCADE;
DROP FUNCTION isclosed (geometry) CASCADE;
DROP FUNCTION centroid (geometry) CASCADE;
DROP FUNCTION isring (geometry) CASCADE;
DROP FUNCTION pointonsurface (geometry) CASCADE;
DROP FUNCTION xmin (box3d) CASCADE;
DROP FUNCTION ymin (box3d) CASCADE;
DROP FUNCTION zmin (box3d) CASCADE;
DROP FUNCTION xmax (box3d) CASCADE;
DROP FUNCTION ymax (box3d) CASCADE;
DROP FUNCTION zmax (box3d) CASCADE;
DROP FUNCTION box3dtobox (box3d) CASCADE;
DROP FUNCTION geom_accum  (geometry[],geometry) CASCADE;
DROP FUNCTION combine_bbox (box3d,geometry) CASCADE;
DROP FUNCTION collector (geometry,geometry) CASCADE;
DROP FUNCTION collect_garray  (geometry[]) CASCADE;
DROP FUNCTION geometry_overleft (geometry, geometry) CASCADE;
DROP FUNCTION geometry_overright (geometry, geometry) CASCADE;
DROP FUNCTION geometry_left (geometry, geometry) CASCADE;
DROP FUNCTION geometry_right (geometry, geometry) CASCADE;
DROP FUNCTION geometry_contain (geometry, geometry) CASCADE;
DROP FUNCTION geometry_contained (geometry, geometry) CASCADE;
DROP FUNCTION geometry_overlap (geometry, geometry) CASCADE;
DROP FUNCTION geometry_same (geometry, geometry) CASCADE;
DROP FUNCTION geometry_lt (geometry, geometry) CASCADE;
DROP FUNCTION geometry_le (geometry, geometry) CASCADE;
DROP FUNCTION geometry_gt (geometry, geometry) CASCADE;
DROP FUNCTION geometry_ge (geometry, geometry) CASCADE;
DROP FUNCTION geometry_eq (geometry, geometry) CASCADE;
DROP FUNCTION geometry_cmp (geometry, geometry) CASCADE;
DROP FUNCTION force_2d (geometry) CASCADE;
DROP FUNCTION force_3d (geometry) CASCADE;
DROP FUNCTION force_collection (geometry) CASCADE;
DROP FUNCTION intersection (geometry,geometry) CASCADE;
DROP FUNCTION buffer (geometry,float8) CASCADE;
DROP FUNCTION convexhull (geometry) CASCADE;
DROP FUNCTION difference (geometry,geometry) CASCADE;
DROP FUNCTION boundary (geometry) CASCADE;
DROP FUNCTION symdifference (geometry,geometry) CASCADE;
DROP FUNCTION symmetricdifference (geometry,geometry) CASCADE;
DROP FUNCTION GeomUnion (geometry,geometry) CASCADE;
DROP FUNCTION unite_garray  (geometry[]) CASCADE;
DROP FUNCTION relate (geometry,geometry) CASCADE;
DROP FUNCTION relate (geometry,geometry,text) CASCADE;
DROP FUNCTION disjoint (geometry,geometry) CASCADE;
DROP FUNCTION touches (geometry,geometry) CASCADE;
DROP FUNCTION intersects (geometry,geometry) CASCADE;
DROP FUNCTION crosses (geometry,geometry) CASCADE;
DROP FUNCTION within (geometry,geometry) CASCADE;
DROP FUNCTION contains (geometry,geometry) CASCADE;
DROP FUNCTION overlaps (geometry,geometry) CASCADE;
DROP FUNCTION isvalid (geometry) CASCADE;
DROP FUNCTION geosnoop (geometry) CASCADE;
DROP FUNCTION simplify (geometry, float8) CASCADE;
DROP FUNCTION ggeometry_consistent (internal,geometry,int4) CASCADE;
DROP FUNCTION ggeometry_compress (internal) CASCADE;
DROP FUNCTION rtree_decompress (internal) CASCADE;
DROP FUNCTION gbox_penalty (internal,internal,internal) CASCADE;
DROP FUNCTION gbox_picksplit (internal, internal) CASCADE;
DROP FUNCTION gbox_union (bytea, internal) CASCADE;
DROP FUNCTION gbox_same (box, box, internal) CASCADE;
DROP FUNCTION geometry_union (geometry,geometry) CASCADE;
DROP FUNCTION geometry_size (geometry,opaque) CASCADE;
DROP FUNCTION AddGeometryColumn (varchar,varchar,varchar,varchar,integer,varchar,integer) CASCADE;
DROP FUNCTION AddGeometryColumn (varchar,varchar,varchar,integer,varchar,integer) CASCADE;
DROP FUNCTION AddGeometryColumn (varchar,varchar,integer,varchar,integer) CASCADE;
DROP FUNCTION DropGeometryColumn (varchar, varchar,varchar,varchar) CASCADE;
DROP FUNCTION DropGeometryColumn (varchar,varchar,varchar) CASCADE;
DROP FUNCTION DropGeometryColumn (varchar,varchar) CASCADE;
DROP FUNCTION DropGeometryTable (varchar, varchar,varchar) CASCADE;
DROP FUNCTION DropGeometryTable (varchar,varchar) CASCADE;
DROP FUNCTION DropGeometryTable (varchar) CASCADE;
DROP FUNCTION update_geometry_stats () CASCADE;
DROP FUNCTION update_geometry_stats (varchar,varchar) CASCADE;
DROP FUNCTION create_histogram2d (box3d,int) CASCADE;
DROP FUNCTION build_histogram2d  (histogram2d,text,text) CASCADE;
DROP FUNCTION build_histogram2d  (histogram2d,text,text,text) CASCADE;
DROP FUNCTION explode_histogram2d  (HISTOGRAM2D,text) CASCADE;
DROP FUNCTION estimate_histogram2d (HISTOGRAM2D,box) CASCADE;
DROP FUNCTION AsSvg (geometry,int4,int4) CASCADE;
DROP FUNCTION AsSvg (geometry,int4) CASCADE;
DROP FUNCTION AsSvg (geometry) CASCADE;
-- Drop all types.
DROP TYPE histogram2d  CASCADE;
DROP TYPE box3d  CASCADE;
DROP TYPE spheroid  CASCADE;
DROP TYPE wkb  CASCADE;
DROP TYPE chip  CASCADE;
DROP TYPE geometry  CASCADE;
-- Drop all tables.
DROP TABLE spatial_ref_sys;
DROP TABLE geometry_columns;

COMMIT;
