------------------------------------------------------------
--[1000219]--  Componente CI 
------------------------------------------------------------
INSERT INTO apex_objeto (proyecto, objeto, anterior, reflexivo, clase_proyecto, clase, subclase, subclase_archivo, objeto_categoria_proyecto, objeto_categoria, nombre, titulo, colapsable, descripcion, fuente_datos_proyecto, fuente_datos, solicitud_registrar, solicitud_obj_obs_tipo, solicitud_obj_observacion, parametro_a, parametro_b, parametro_c, parametro_d, parametro_e, parametro_f, usuario, creacion) VALUES ('toba_referencia', '1000219', NULL, NULL, 'toba', 'objeto_ci', NULL, NULL, NULL, NULL, 'Componente CI', 'Controlador de Interface', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2006-11-29 17:25:47');
INSERT INTO apex_objeto_mt_me (objeto_mt_me_proyecto, objeto_mt_me, ev_procesar_etiq, ev_cancelar_etiq, ancho, alto, posicion_botonera, tipo_navegacion, con_toc, incremental, debug_eventos, activacion_procesar, activacion_cancelar, ev_procesar, ev_cancelar, objetos, post_procesar, metodo_despachador, metodo_opciones) VALUES ('toba_referencia', '1000219', NULL, NULL, '80%', NULL, 'abajo', 'wizard', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO apex_objeto_ci_pantalla (objeto_ci_proyecto, objeto_ci, pantalla, identificador, orden, etiqueta, descripcion, tip, imagen_recurso_origen, imagen, objetos, eventos, subclase, subclase_archivo) VALUES ('toba_referencia', '1000219', '1000081', 'agenda', '1', 'Agenda', NULL, NULL, NULL, NULL, NULL, NULL, 'pant_agenda', 'tutorial/pant_tutorial.php');
INSERT INTO apex_objeto_ci_pantalla (objeto_ci_proyecto, objeto_ci, pantalla, identificador, orden, etiqueta, descripcion, tip, imagen_recurso_origen, imagen, objetos, eventos, subclase, subclase_archivo) VALUES ('toba_referencia', '1000219', '1000082', 'definicion', '2', '¿Qué es un CI?', NULL, NULL, NULL, NULL, NULL, NULL, 'pant_definicion', 'tutorial/pant_ci.php');
INSERT INTO apex_objeto_ci_pantalla (objeto_ci_proyecto, objeto_ci, pantalla, identificador, orden, etiqueta, descripcion, tip, imagen_recurso_origen, imagen, objetos, eventos, subclase, subclase_archivo) VALUES ('toba_referencia', '1000219', '1000086', 'ejemplo', '3', 'Ejemplo', NULL, NULL, NULL, NULL, NULL, NULL, 'pant_ejemplo', 'tutorial/pant_ci.php');
INSERT INTO apex_objeto_ci_pantalla (objeto_ci_proyecto, objeto_ci, pantalla, identificador, orden, etiqueta, descripcion, tip, imagen_recurso_origen, imagen, objetos, eventos, subclase, subclase_archivo) VALUES ('toba_referencia', '1000219', '1000089', 'video', '4', '[video] Creación del componentes del ejemplo', NULL, NULL, NULL, NULL, NULL, NULL, 'pant_video', 'tutorial/pant_ci.php');
INSERT INTO apex_objeto_ci_pantalla (objeto_ci_proyecto, objeto_ci, pantalla, identificador, orden, etiqueta, descripcion, tip, imagen_recurso_origen, imagen, objetos, eventos, subclase, subclase_archivo) VALUES ('toba_referencia', '1000219', '1000090', 'eventos', '5', 'Atención de eventos', NULL, NULL, NULL, NULL, NULL, NULL, 'pant_eventos', 'tutorial/pant_ci.php');
INSERT INTO apex_objeto_ci_pantalla (objeto_ci_proyecto, objeto_ci, pantalla, identificador, orden, etiqueta, descripcion, tip, imagen_recurso_origen, imagen, objetos, eventos, subclase, subclase_archivo) VALUES ('toba_referencia', '1000219', '1000091', 'configuracion', '6', 'Configuración', NULL, NULL, NULL, NULL, NULL, NULL, 'pant_configuracion', 'tutorial/pant_ci.php');
INSERT INTO apex_objeto_ci_pantalla (objeto_ci_proyecto, objeto_ci, pantalla, identificador, orden, etiqueta, descripcion, tip, imagen_recurso_origen, imagen, objetos, eventos, subclase, subclase_archivo) VALUES ('toba_referencia', '1000219', '1000092', 'sesion', '7', 'Propiedades en sesión', NULL, NULL, NULL, NULL, NULL, NULL, 'pant_sesion', 'tutorial/pant_ci.php');
INSERT INTO apex_objeto_ci_pantalla (objeto_ci_proyecto, objeto_ci, pantalla, identificador, orden, etiqueta, descripcion, tip, imagen_recurso_origen, imagen, objetos, eventos, subclase, subclase_archivo) VALUES ('toba_referencia', '1000219', '1000093', 'navegacion', '8', 'Cambios a la navegación', NULL, NULL, NULL, NULL, NULL, NULL, 'pant_navegacion', 'tutorial/pant_ci.php');
