INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_21000','toba','error','CARDINALITY VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22000','toba','error','DATA EXCEPTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22001','toba','error','STRING DATA RIGHT TRUNCATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22002','toba','error','NULL VALUE NO INDICATOR PARAMETER');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22003','toba','error','NUMERIC VALUE OUT OF RANGE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22004','toba','error','NULL VALUE NOT ALLOWED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22005','toba','error','ERROR IN ASSIGNMENT');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22007','toba','error','INVALID DATETIME FORMAT');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22008','toba','error','DATETIME FIELD OVERFLOW');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22009','toba','error','INVALID TIME ZONE DISPLACEMENT VALUE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22010','toba','error','INVALID INDICATOR PARAMETER VALUE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22011','toba','error','SUBSTRING ERROR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22012','toba','error','DIVISION BY ZERO');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22015','toba','error','INTERVAL FIELD OVERFLOW');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22018','toba','error','INVALID CHARACTER VALUE FOR CAST');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22019','toba','error','INVALID ESCAPE CHARACTER');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22020','toba','error','INVALID LIMIT VALUE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22021','toba','error','CHARACTER NOT IN REPERTOIRE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22022','toba','error','INDICATOR OVERFLOW');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22023','toba','error','INVALID PARAMETER VALUE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22024','toba','error','UNTERMINATED C STRING');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22025','toba','error','INVALID ESCAPE SEQUENCE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22026','toba','error','STRING DATA LENGTH MISMATCH');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22027','toba','error','TRIM ERROR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_23000','toba','error','INTEGRITY CONSTRAINT VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_23001','toba','error','RESTRICT VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_23502','toba','error','NOT NULL VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_23503','toba','error','FOREIGN KEY VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_23505','toba','error','UNIQUE VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_23514','toba','error','CHECK VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_24000','toba','error','INVALID CURSOR STATE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25000','toba','error','INVALID TRANSACTION STATE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25001','toba','error','ACTIVE SQL TRANSACTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25002','toba','error','BRANCH TRANSACTION ALREADY ACTIVE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25003','toba','error','INAPPROPRIATE ACCESS MODE FOR BRANCH TRANSACTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25004','toba','error','INAPPROPRIATE ISOLATION LEVEL FOR BRANCH TRANSACTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25005','toba','error','NO ACTIVE SQL TRANSACTION FOR BRANCH TRANSACTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25006','toba','error','READ ONLY SQL TRANSACTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25007','toba','error','SCHEMA AND DATA STATEMENT MIXING NOT SUPPORTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25008','toba','error','HELD CURSOR REQUIRES SAME ISOLATION LEVEL');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_26000','toba','error','INVALID SQL STATEMENT NAME');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_27000','toba','error','TRIGGERED DATA CHANGE VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_28000','toba','error','INVALID AUTHORIZATION SPECIFICATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_34000','toba','error','INVALID CURSOR NAME');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_38000','toba','error','EXTERNAL ROUTINE EXCEPTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_38001','toba','error','CONTAINING SQL NOT PERMITTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_38002','toba','error','MODIFYING SQL DATA NOT PERMITTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_38003','toba','error','PROHIBITED SQL STATEMENT ATTEMPTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_38004','toba','error','READING SQL DATA NOT PERMITTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_39000','toba','error','EXTERNAL ROUTINE INVOCATION EXCEPTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_39001','toba','error','INVALID SQLSTATE RETURNED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_39004','toba','error','NULL VALUE NOT ALLOWED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_40000','toba','error','TRANSACTION ROLLBACK');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_40001','toba','error','SERIALIZATION FAILURE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_40002','toba','error','INTEGRITY CONSTRAINT VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_40003','toba','error','STATEMENT COMPLETION UNKNOWN');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42000','toba','error','SYNTAX ERROR OR ACCESS RULE VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42501','toba','error','INSUFFICIENT PRIVILEGE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42601','toba','error','SYNTAX ERROR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42602','toba','error','INVALID NAME');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42611','toba','error','INVALID COLUMN DEFINITION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42622','toba','error','NAME TOO LONG');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42701','toba','error','DUPLICATE COLUMN');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42702','toba','error','AMBIGUOUS COLUMN');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42703','toba','error','UNDEFINED COLUMN');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42704','toba','error','UNDEFINED OBJECT');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42710','toba','error','DUPLICATE OBJECT');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42712','toba','error','DUPLICATE ALIAS');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42723','toba','error','DUPLICATE FUNCTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42725','toba','error','AMBIGUOUS FUNCTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42803','toba','error','GROUPING ERROR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42804','toba','error','DATATYPE MISMATCH');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42809','toba','error','WRONG OBJECT TYPE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42830','toba','error','INVALID FOREIGN KEY');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42846','toba','error','CANNOT COERCE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42883','toba','error','UNDEFINED FUNCTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42939','toba','error','RESERVED NAME');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_44000','toba','error','WITH CHECK OPTION VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_53000','toba','error','INSUFFICIENT RESOURCES');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_53100','toba','error','DISK FULL');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_53200','toba','error','OUT OF MEMORY');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_53300','toba','error','TOO MANY CONNECTIONS');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_54000','toba','error','PROGRAM LIMIT EXCEEDED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_54001','toba','error','STATEMENT TOO COMPLEX');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_54011','toba','error','TOO MANY COLUMNS');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_54023','toba','error','TOO MANY ARGUMENTS');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_55000','toba','error','OBJECT NOT IN PREREQUISITE STATE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_55006','toba','error','OBJECT IN USE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_57000','toba','error','OPERATOR INTERVENTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_57014','toba','error','QUERY CANCELED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_58030','toba','error','IO ERROR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_00000','toba','info','SUCCESSFUL COMPLETION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_08P01','toba','error','PROTOCOL VIOLATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_01000','toba','error','WARNING');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_01003','toba','error','WARNING NULL VALUE ELIMINATED IN SET FUNCTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_01004','toba','error','WARNING STRING DATA RIGHT TRUNCATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_01008','toba','error','WARNING IMPLICIT ZERO BIT PADDING');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_0100C','toba','error','WARNING DYNAMIC RESULT SETS RETURNED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_02000','toba','error','NO DATA');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_02001','toba','error','NO ADDITIONAL DYNAMIC RESULT SETS RETURNED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_03000','toba','error','SQL STATEMENT NOT YET COMPLETE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_08000','toba','error','CONNECTION EXCEPTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_08001','toba','error','SQLCLIENT UNABLE TO ESTABLISH SQLCONNECTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_08003','toba','error','CONNECTION DOES NOT EXIST');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_08004','toba','error','SQLSERVER REJECTED ESTABLISHMENT OF SQLCONNECTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_08006','toba','error','CONNECTION FAILURE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_08007','toba','error','TRANSACTION RESOLUTION UNKNOWN');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_09000','toba','error','TRIGGERED ACTION EXCEPTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_0A000','toba','error','FEATURE NOT SUPPORTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_0B000','toba','error','INVALID TRANSACTION INITIATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_0F000','toba','error','LOCATOR EXCEPTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_0F001','toba','error','INVALID SPECIFICATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_0L000','toba','error','INVALID GRANTOR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_0LP01','toba','error','INVALID GRANT OPERATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_0P000','toba','error','INVALID ROLE SPECIFICATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2200B','toba','error','ESCAPE CHARACTER CONFLICT');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2200C','toba','error','INVALID USE OF ESCAPE CHARACTER');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2200D','toba','error','INVALID ESCAPE OCTET');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2200F','toba','error','ZERO LENGTH CHARACTER STRING');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2200G','toba','error','MOST SPECIFIC TYPE MISMATCH');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2201B','toba','error','INVALID REGULAR EXPRESSION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2202E','toba','error','ARRAY ELEMENT ERROR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22P01','toba','error','FLOATING POINT EXCEPTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22P02','toba','error','INVALID TEXT REPRESENTATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22P03','toba','error','INVALID BINARY REPRESENTATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22P04','toba','error','BAD COPY FILE FORMAT');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_22P05','toba','error','UNTRANSLATABLE CHARACTER');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25P01','toba','error','NO ACTIVE SQL TRANSACTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_25P02','toba','error','IN FAILED SQL TRANSACTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2B000','toba','error','DEPENDENT PRIVILEGE DESCRIPTORS STILL EXIST');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2BP01','toba','error','DEPENDENT OBJECTS STILL EXIST');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2D000','toba','error','INVALID TRANSACTION TERMINATION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2F000','toba','error','SQL ROUTINE EXCEPTION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2F002','toba','error','MODIFYING SQL DATA NOT PERMITTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2F003','toba','error','PROHIBITED SQL STATEMENT ATTEMPTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2F004','toba','error','READING SQL DATA NOT PERMITTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_2F005','toba','error','FUNCTION EXECUTED NO RETURN STATEMENT');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_39P01','toba','error','TRIGGER PROTOCOL VIOLATED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_39P02','toba','error','SRF PROTOCOL VIOLATED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_3D000','toba','error','INVALID CATALOG NAME');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_3F000','toba','error','INVALID SCHEMA NAME');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_40P01','toba','error','DEADLOCK DETECTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P01','toba','error','UNDEFINED TABLE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P02','toba','error','UNDEFINED PARAMETER');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P03','toba','error','DUPLICATE CURSOR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P04','toba','error','DUPLICATE DATABASE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P05','toba','error','DUPLICATE PSTATEMENT');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P06','toba','error','DUPLICATE SCHEMA');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P07','toba','error','DUPLICATE TABLE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P08','toba','error','AMBIGUOUS PARAMETER');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P09','toba','error','AMBIGUOUS ALIAS');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P10','toba','error','INVALID COLUMN REFERENCE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P11','toba','error','INVALID CURSOR DEFINITION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P12','toba','error','INVALID DATABASE DEFINITION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P13','toba','error','INVALID FUNCTION DEFINITION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P14','toba','error','INVALID PSTATEMENT DEFINITION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P15','toba','error','INVALID SCHEMA DEFINITION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P16','toba','error','INVALID TABLE DEFINITION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P17','toba','error','INVALID OBJECT DEFINITION');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_42P18','toba','error','INDETERMINATE DATATYPE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_55P02','toba','error','CANT CHANGE RUNTIME PARAM');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_57P01','toba','error','ADMIN SHUTDOWN');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_57P02','toba','error','CRASH SHUTDOWN');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_57P03','toba','error','CANNOT CONNECT NOW');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_58P01','toba','error','UNDEFINED FILE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_58P02','toba','error','DUPLICATE FILE');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_F0000','toba','error','CONFIG FILE ERROR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_F0001','toba','error','LOCK FILE EXISTS');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_XX000','toba','error','INTERNAL ERROR');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_XX001','toba','error','DATA CORRUPTED');
INSERT INTO apex_msg (indice, proyecto, msg_tipo, mensaje_b) VALUES ('pg_XX002','toba','error','INDEX CORRUPTED');
